README.md
Switch local docker  to a different route
=> Recommend ip route method for local development again

README.md, daskernetes/core.py, daskernetes/tests/test_core.py
This is kind of gimicky, but plays well
=> Add IPython widget to KubeCluster

daskernetes/core.py, daskernetes/tests/test_core.py
=> Use default namespace and unique name

daskernetes/core.py
I hadn't fully tested the last PR before it was merged.  This resolves a silly typo.
=> Fix adapt method

.circleci/config.yml, ci/environment-3.6.yml, ci/install-circle.sh, daskernetes/core.py, daskernetes/tests/test_core.py, requirements.txt
This PR has two major changes:
1.  It introduces continuous integration testing on Circle-CI 
2.  It changes the test suite to use pytest fixtures.  In particular these fixtures run tests within a new namespace and clean up that namespace on terminating the test.
cc @yuvipanda if you have time to review
=> Continuous Integration, and Pytest Fixtures

README.md
Fixes #11 
cc @yuvipanda @jacobtomlinson @mkjpryor-stfc
=> Add history section to README

.circleci/config.yml, ci/environment-3.6.yml, daskernetes/tests/test_core.py
=> Pin versions for dask and distributed

dask_kubernetes/core.py, dask_kubernetes/tests/test_core.py
Otherwise bad usernames can cause connection errors
=> Escape username

dask_kubernetes/core.py, doc/source/index.rst
=> Clarify expected uses cases, and how the Kubernetes cluster is found

dask_kubernetes/core.py, dask_kubernetes/tests/test_core.py
I'm a little curious to know if there are good reasons against this.
=> Include username in metadata

dask_kubernetes/core.py, dask_kubernetes/tests/test_core.py
Confirmed that this PR resolves #95.
=> Ensure dask.pydata.org/cluster-name value is escaped

dask_kubernetes/core.py, requirements.txt, setup.py
=> Drop python 2

.pre-commit-config.yaml, dask_kubernetes/__init__.py, dask_kubernetes/auth.py, dask_kubernetes/config.py, dask_kubernetes/core.py, dask_kubernetes/objects.py, dask_kubernetes/tests/conftest.py, dask_kubernetes/tests/test_async.py, dask_kubernetes/tests/test_objects.py, dask_kubernetes/tests/test_sync.py, setup.py
Fixes #120 
The first commit applies black to existing code
The second commit adds a pre-commit config file to make it automatic
=> Use Black for auto-formatting

dask_kubernetes/core.py, dask_kubernetes/tests/test_async.py
See https://github.com/pangeo-data/pangeo/issues/562#issuecomment-468803018
=> fix await self.scale line

dask_kubernetes/config.py
Recent versions of pyyaml now raise warnings on yaml.load
=> Use yaml.safe_load

ci/environment-3.6.yml, dask_kubernetes/core.py, dask_kubernetes/tests/test_core.py, requirements.txt, setup.py
=> k8s API changed in 9.0

.circleci/config.yml, .pre-commit-config.yaml, ci/environment-3.6.yml, dask_kubernetes/__init__.py, dask_kubernetes/_version.py, dask_kubernetes/auth.py, dask_kubernetes/config.py, dask_kubernetes/core.py, dask_kubernetes/logs.py, dask_kubernetes/objects.py, dask_kubernetes/tests/conftest.py, dask_kubernetes/tests/test_core.py, dask_kubernetes/tests/test_objects.py, setup.py
Two real commits
1. https://github.com/dask/dask-kubernetes/commit/7ca78da4bbf881b9d83e0a4551eea78eaef67e4f: Applying black
2. https://github.com/dask/dask-kubernetes/commit/856efb221d4c4b6faa01319deddb2a5790f609a0: Adding to the CI and a pre-commit-config
I also have a third commit with bad formatting to check if CI fails.
=> Apply Black

.circleci/config.yml, ci/environment-3.7.yml
=> Add conda and setuptools to test environment

dask_kubernetes/core.py
=> Raise exception if retries are exhausted

doc/source/conf.py, doc/source/index.rst
=> DOC: further install instructions and KubeCluster hyperlink

doc/source/conf.py, versioneer.py
Not sure what changed here but some files are failing black checks all of a sudden.
Formatting them with black.
=> Some files are failing black checks for some reason

setup.py
Resolves https://github.com/dask/dask-kubernetes/issues/269
=> bump minimum python version to 3.7

doc/source/kubecluster.rst
Resolves https://github.com/dask/dask-kubernetes/issues/144
This is a first pass at getting a working example and updating docs on using dask-kubernetes with GPUs (this has been coming up a more for me and having some docs I can point to would be very valuable)
Also adds docs on remote deploys
=> Doc Updates

dask_kubernetes/helm.py
Not sure if others would find this useful but in our case we deploy our own helm chart that's based on, but not identical to, the standard Dask chart. In particular the deployment names are slightly different, so the hard-coded versions in `HelmCluster` don't work for us.
For now I'm just monkey patching the functions with hard-coded deployment names but it doesn't seem like it'd hurt to make it configurable 🙂.
=> Make deployment names configurable in HelmCluster

doc/source/testing.rst
Closes #288 
I believe these changes to the docs make it easier for people to understand how to get this up and running.
Maybe the docs should also refer to this setup from quickstart?
=> Clarify how to run tests locally

.github/workflows/release.yml, README.rst, doc/source/releasing.rst
Add release CI which tests building packages on every run and pushed to PyPI on tags.
Also documented release process and added some badges to the README.
=> Add release CI, docs and README badges

requirements.txt
=> Bump kubernetes package dependencies

dask_kubernetes/tests/test_helm.py, dask_kubernetes/utils.py
fixes https://github.com/dask/dask-kubernetes/issues/311 and https://github.com/dask/dask-kubernetes/issues/321.
=> Prevent collisions in port-forward and use namespaces while port-forwarding

dask_kubernetes/objects.py
Closes https://github.com/dask/dask-kubernetes/issues/183
=> Add annotations to dask pods

doc/source/testing.rst
Updated the testing docs to make them more explicit as to the necessary steps when setting up the project for newcomers
=> Update Testing documentation

dask_kubernetes/core.py
=> Convert scheduler_pod_template from str and dict

dask_kubernetes/tests/test_async.py, dask_kubernetes/tests/test_helm.py, dask_kubernetes/tests/test_kind.py, dask_kubernetes/tests/test_sync.py, dask_kubernetes/utils.py, requirements-test.txt, setup.cfg
Trying to fix #382.
I also noticed that `dask_kubernetes/tests/test_helm.py::test_discovery` failed locally for me due to my local Dask config. So tweaked that test to set its own config.
=> Fix up some tests

dask_kubernetes/operator/tests/test_operator.py
Lets us develop the operator with TDD.
=> Add tests to Operator for TDD

dask_kubernetes/core.py, dask_kubernetes/kubernetes.yaml, dask_kubernetes/utils.py
=> Retry service name resolution socket.getaddrinfo several times

dask_kubernetes/operator/core.py, dask_kubernetes/operator/daskcluster.py, dask_kubernetes/operator/tests/test_operator.py
As a part of the review for #392, we want to ensure support for multiple dask clusters.
=> Support Multiple Clusters

dask_kubernetes/operator/core.py, dask_kubernetes/operator/daskcluster.py, dask_kubernetes/operator/tests/test_operator.py, dask_kubernetes/utils.py
As a part of #392. This PR adds a Singleton class for tracking Dask RPC objects.
=> Singleton Class for Dask RPC

dask_kubernetes/operator/customresources/daskcluster.yaml, dask_kubernetes/operator/customresources/daskworkergroup.yaml, dask_kubernetes/operator/daskcluster.py, dask_kubernetes/operator/tests/resources/simpleworkergroup.yaml
As a part of #392. We want to lock down the required properties for the CRDs
=> Add properties to dask custom resources definitions

dask_kubernetes/operator/tests/test_operator.py
Reverts dask/dask-kubernetes#432
Pressed the wrong button 😅
=> Revert "Fix tests"

dask_kubernetes/operator/core.py, dask_kubernetes/operator/daskcluster.py, dask_kubernetes/operator/deployment/manifest.yaml
As a part of #392, we want the operator to run in a separate pod. This PR is to update the manifest/docker file as needed to get it working
=> Fix docker file to Start the Operator in a Running Pod

dask_kubernetes/experimental/kubecluster.py, doc/source/operator.rst
Raise not implemented error for adapt. And add missing methods from `KubeCluster` to the methods section
=> Operator docs

dask_kubernetes/experimental/kubecluster.py, doc/source/operator.rst
Add parameters and examples to methods in `KubeCluster`
=> Update docstrings in `KubeCluster` methods

dask_kubernetes/classic/kubecluster.py
Update to documentation - fixes #494
=> fix typo in docstring

dask_kubernetes/classic/kubecluster.py, dask_kubernetes/common/objects.py
=> fix: Preserve custom pod affinities

doc/source/installing.rst
=> Update docs with CI matrix info

.pre-commit-config.yaml, ci/pre-commit-crd.py, dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskcluster.yaml, dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskjob.yaml, dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskworkergroup.yaml, dask_kubernetes/operator/deployment/manifests/daskcluster.yaml, dask_kubernetes/operator/deployment/manifests/daskjob.yaml, dask_kubernetes/operator/deployment/manifests/daskworkergroup.yaml, requirements-test.txt
Reverts #555 and rolls onto k8s-crd-resolver v0.12.0
=> Revert pinning to roll onto k8s-crd-resolver v0.12.0

dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/serviceaccount.yaml
This PR adds the `daskworkergroups/scale` resource in the `clusterrole` rules.
Without it, the `dask-operator` pod fails when we try to adapt the cluster:
```
[2022-10-18 01:36:27,743] kopf.objects         [ERROR   ] [dask/dask-john-c69a8bde-a] Timer 'daskautoscaler_adapt' failed with an exception. Will retry.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
result = await invoke_handler(
File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
result = await invocation.invoke(
File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
result = await fn(**kwargs)  # type: ignore
File …
```
=> Add daskworkergroups/scale in the cluster role rules

doc/source/operator_kubecluster.rst
This came up in a [forum question](https://dask.discourse.group/t/dask-kubernetes-usage/1285/6) and it seems like a common question so adding it to the docs.
The `make_cluster_spec` creation method makes customisations like this possible.
```bash
kubectl create secret docker-registry regcred \
--docker-server=<your-registry-server> \
--docker-username=<your-name> \
--docker-password=<your-pword> \
--docker-email=<your-email>
```
```python
from dask_kubernetes.operator import KubeCluster, make_cluster_spec
spec = make_cluster_spec(name="custom", image="foo.com/jacobtomlinson/dask:latest")
spec["spec"]["worker"]["spec"]["imagePullSecrets"] = [{"name": "regcred"}]
spec["spec"]["scheduler"]["spec"]["imagePullSecrets"] = [{"name": "regcred"}]
cluster = KubeCluster(custom_cluster_spec=spec)
```
=> Document pulling from a private container registry

dask_kubernetes/classic/kubecluster.py
=> Add retries to deletion

requirements.txt
Fixes https://github.com/dask/dask-kubernetes/issues/620#issuecomment-1330845244
=> Adds `pykube` as dependency

doc/source/testing.rst
Installing PR versions of the controller for testing has come up a few times lately so documenting it here.
=> Document installing the controller from a PR

dask_kubernetes/operator/controller/controller.py
I extracted these lines from #649. That PR seems to keep getting stuck in CI so I thought I'd break it down into some smaller chunks that we can merge more quickly and get to the bottom of the hang.
=> Retire workers during scale down

doc/source/index.rst
=> Fix invalid name typo

doc/requirements-docs.txt, doc/source/conf.py, doc/source/operator_installation.rst
Add [frigate](https://github.com/rapidsai/frigate) Sphinx extension to autodoc the helm chart config.
=> Frigate helm config

dask_kubernetes/operator/controller/controller.py
Closes #654 If a kopf handler fails, the resources it creates are not created again; preventing an `AlreadyExists` exception.
=> Add checks for scheduler, service, and worker groups

.github/workflows/helmcluster.yaml, .github/workflows/kubecluster.yaml, .github/workflows/operator.yaml, README.rst
Updating Kubernetes versions in CI to 1.24-1.27.
=> Bump CI to Kubernetes 1.27

.github/workflows/helmcluster.yaml, .github/workflows/kubecluster.yaml, .github/workflows/lint.yaml, .github/workflows/operator.yaml, .github/workflows/release.yml, .readthedocs.yaml, README.rst, ci/Dockerfile, dask_kubernetes/operator/deployment/Dockerfile, doc/source/index.rst, doc/source/kubecluster.rst, setup.py
Dask and Distributed have dropped Python 3.8. Time to drop it here too.
=> Drop Python 3.8

dask_kubernetes/operator/controller/tests/test_controller.py
The job tests have been disabled as they've been disabled in CI as they've been failing. This PR brings those back. More context in https://github.com/dask/dask-kubernetes/pull/736
@jacobtomlinson turns out they've been failing because the namespace has not been passed correctly to all `kubectl` commands - should be good now 👍 
As for the race condition in [this message](https://github.com/dask/dask-kubernetes/pull/736#issuecomment-1595819375), I'll open a separate PR.
Closes https://github.com/dask/dask-kubernetes/issues/735
=> Fix job test

requirements.txt
Bump kr8s to 0.6.0 which should contain the fix for #751
=> Bump kr8s to 0.6.0

requirements-test.txt, requirements.txt
Bumping kr8s so we can use some of the new syntactic sugar.
=> Bump kr8s to 0.8.1

dask_kubernetes/operator/controller/controller.py
Just replaces the use of `kubernetes_asyncio` with `kr8s` in `retire_workers`. Should functionally have no change.
=> Update retire_workers to use kr8s

dask_kubernetes/operator/controller/controller.py
Just replaces the use of `kubernetes_asyncio` with `kr8s` in `daskjob_create_components`. Should functionally have no change.
=> Update daskjob_create_components to use kr8s

doc/source/kubecluster.rst
=> Fix extensibility section link on kubecluster.rst

dask_kubernetes/operator/kubecluster/kubecluster.py
Pulling out another chunk of #785. This one updates `KubeCluster.get_logs()` to use `kr8s`.
=> Migrate KubeCluster get_logs to kr8s

dask_kubernetes/operator/kubecluster/kubecluster.py
Pulling out another chunk of #785. This one updates `KubeCluster.add_worker_group()` and `KubeCluster.delete_worker_group()` to use `kr8s`.
=> Migrate KubeCluster worker group management to kr8s #787

dask_kubernetes/common/networking.py
=> Make waiting for scheduler Pod more robust

dask_kubernetes/operator/kubecluster/kubecluster.py, requirements.txt
kr8s 0.8.9 can wait for load balancers so simplifying the code here to use that.
=> Use kr8s to wait for service

dask_kubernetes/operator/kubecluster/kubecluster.py
Pulling out another chunk of #785. This one updates `KubeCluster._wait_for_controller()` to use `kr8s`. This also removes the last usage of `aiopykube` so cleaned up some imports and setup from that.
=> Migrate KubeCluster wait for controller to kr8s

requirements.txt
=> Bump kr8s to 0.8.15

dask_kubernetes/operator/kubecluster/kubecluster.py
This PR adds type hints to the `operator.KubeCluster` constructor. I ran `isort` since there were a few additional imports. Hope you don't mind the nit, but I also corrected two minor typos in the docstring. 
There's some type hint redundancy between the parameters and the docstring. I usually exclude type hints from docstrings to avoid that, but TBH I'm not sure if that's idiomatic. [asyncio](https://github.com/python/cpython/blob/0b6b05391bcc5893d2b71032cb704995696ecd0b/Lib/asyncio/staggered.py#L16) in the stdlib seems to adhere to that pattern fwiw. Happy to strip the type hints from the docstring if you think it makes sense.
If this PR seems reasonable and gets merged, happy to add type hints elsewhere in the codebase and run mypy and stuff.
Lastly, it might make sense to add [isort …
=> Add type hints to KubeCluster constructor

dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md, dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
=> Enable read-only root filesystem.

.github/workflows/operator.yaml, ci/Dockerfile, requirements.txt
CI seems unhappy here lately. Pushing a small comment change to a file that should trigger all CI jobs.
=> Investigate CI

dask_kubernetes/operator/go_client/pkg/client/applyconfiguration/kubernetes.dask.org/v1/daskclusterstatus.go, dask_kubernetes/operator/go_client/pkg/client/applyconfiguration/kubernetes.dask.org/v1/daskjobstatus.go, dask_kubernetes/operator/go_client/pkg/client/applyconfiguration/utils.go
=> Fix versions in the go client

README.rst, doc/source/index.rst
Follow on to #862 to update README/docs badges.
=> Bump Kubernetes badges to 1.26-1.29

README.rst
Looks like the CI badge in the README broke at some point.
This PR adds a few new CI badges.
=> Update CI badges

README.rst, doc/source/index.rst
In #864 I accidentally added 3.12 to the README/docs badges. Removing again for now.
=> Remove 3.12 from badge

dask_kubernetes/operator/controller/controller.py, dask_kubernetes/operator/controller/tests/test_controller.py
- Fixes https://github.com/dask/dask-kubernetes/issues/841
- Small code quality cleanup
=> Fix issue of duplicated environment variables

dask_kubernetes/operator/controller/controller.py
Partially resolves #882 by reducing log noise.
=> Set a default value on idleTimeout

docs/source/operator_resources.rst
Closes #922 
Follow up to #672
=> Add DaskCluster.idleTimeout to the docs

dask_kubernetes/operator/_objects.py, dask_kubernetes/operator/controller/controller.py, dask_kubernetes/operator/controller/tests/test_controller.py, dask_kubernetes/operator/kubecluster/discovery.py, dask_kubernetes/operator/kubecluster/kubecluster.py, dask_kubernetes/operator/networking.py, pyproject.toml
=> Bump kr8s to v0.20.*
