dask/dask-kubernetes

- daskernetes/tests/test_objects.py
This includes failures in the deserialize method that we saw when
deploying pangeo.pydata.org
> Add failing test for make_pod_from_dict

- daskernetes/core.py
- daskernetes/objects.py
- daskernetes/tests/conftest.py
- daskernetes/tests/test_core.py
- daskernetes/tests/test_objects.py
- Add config options for memory / cpu limits and guarantees
- Allow an easier escape hatch with `extra_container_config` and 
`extra_pod_config`, which are dicts that are deep merged into the 
pod / container configuration
- Minor other cleanups
> Make KubeCluster more configurable

- daskernetes/core.py
Also change testing from 3.6 to 3.5.
At some point we should test both, but until then 3.5 is probably safer,
because of backwards compatibility.
> Support Python 3.5

- daskernetes/core.py
- daskernetes/tests/test_core.py
- doc/source/index.rst
Previously we could only scale up by number of workers.
To scale down we needed to specify the precise workers to kill
(this was normally handled by the scheduler in adaptive mode).
However sometimes you just want to manually control the size of the
cluster.
This implements a simple heuristic, to first choose the idle workers
then then prefer workers with less memory use.
> Add generic scale (up or down) function

- daskernetes/core.py
- daskernetes/objects.py
- daskernetes/tests/test_core.py
We do this both by inserting dummy values,
and by raising informative errors
> Support receiving overly-simple specs without metadata/names

- daskernetes/__init__.py
- daskernetes/config.py
- daskernetes/core.py
- daskernetes/tests/test_core.py
This allows users to launch a KubeCluster() with no arguments if the
worker pod spec is in a yaml file pointed to by
the DASKERNETES_WORKER_SPEC_PATH environment variable.
This commit also creates a config.py file that contains daskernetes
configuration, which is currently just taken from environment variables.
> Automatically read worker yaml file from env variable

- daskernetes/core.py
- daskernetes/tests/test_core.py
- doc/source/index.rst
This allows us to set the diagnostics link shown in the KubeCluster widget with an arbitrary formatted strings like the following example from a JupyterHub deployment with nbserverproxy running:
export DASKERNETES_DIAGNOSTICS_LINK="{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status"
The widget looks for this environment variable and populates it with `.format(host=host, port=port, **os.environ)`
cc @yuvipanda
> Set diagnostics link with environment variable

- daskernetes/core.py
- daskernetes/tests/test_core.py
- doc/source/index.rst
This PR allows you to customise the worker name template with the environment variable `DASKERNETES_WORKER_NAME_TEMPLATE`. If not specified it falls back to `dask-{user}-{uuid}`.
The template is then formatted with `user` and `uuid` as before but also it unpacks `os.environ` to allow the use of environment variables in the template.
For example in my use case I'm keen to configure the template to `dask-{JUPYTERHUB_USER}-{uuid}` as the `user` is always `jovyan`.
> Allow customisation of worker name in environment

- ci/environment-3.6.yml
- dask_kubernetes/core.py
- dask_kubernetes/tests/test_core.py
- doc/source/index.rst
- requirements.txt
This generalizes the widget and adapt work in dask-kubernetes to upstream
This is not yet mergable.  We'll have to wait for an upstream release.
> Use Cluster superclass in distributed.deploy to remove functionality

- doc/source/index.rst
The quickstart won't run without it.
> Specify container name in quick start

- dask_kubernetes/tests/test_core.py
- dask_kubernetes/tests/test_objects.py
- doc/source/index.rst
The following PR tries to use `'imagePullPolicy': 'IfNotPresent'` as much as possible in the pod specs used in the tests (only those that actually spawn worker pods) so as to accelerate the speed of the tests (both on the CI and on the local machine).
> Do not pull daskdev/dask image for each test

- .circleci/config.yml
- dask_kubernetes/core.py
- dask_kubernetes/tests/test_core.py
When scaling down a cluster with pending pods still being provisioned in the background, one can often get an `AssertionError` in  `select_workers_to_close`. Furthermore, running workers are deleted before pending pods have a chance to get up and running when using a saturated shared kubernetes cluster. This trashes intermediate computation results for no valid reason and makes everything much slower than necessary.
This PR fixes all of that by always trying to scale down non-running pods first. Furthermore, we now explicitly scale down running pods by first scheduling `self.scheduler.retire_workers` in the event loop to make sure that we have the time to migrate intermediate results back to the remaining running workers.
I have added (stress) tests for all the above. …
> Delete pending pods first when manually scaling down

- dask_kubernetes/core.py
- dask_kubernetes/tests/test_core.py
Partially addresses #56.
This PR updated the `KubeCluster.logs()` method to make the `pod` kwarg optional. Now if you omit the kwarg it will return you a dictionary of logs by pod IP.
> Update logs to make specifying a pod optional

- dask_kubernetes/core.py
- dask_kubernetes/tests/test_core.py
I believe #75 broke reading pod template from `kubernetes.worker-template`.
If `kubernetes.worker-template` is set, `pod_template` becomes a truthy value (by the line I removed), and the following code will never run:
https://github.com/dask/dask-kubernetes/blob/c4728ba4ecf87c175f3b2020f3ffb0a91860b6d0/dask_kubernetes/core.py#L159-L161
Later on, since `make_pod_from_dict` was never called, the following code will raise an exception since `pod_template` at this point is still a `dict`.
https://github.com/dask/dask-kubernetes/blob/c4728ba4ecf87c175f3b2020f3ffb0a91860b6d0/dask_kubernetes/core.py#L193
> Fix broken worker-template configuration

- dask_kubernetes/core.py
- dask_kubernetes/tests/test_core.py
Digging a bit deeper into #90, I think I found the issue.
So I started 6 workers, one of them got evicted, and then my logs got flooded with
```
2018-08-03 08:24:50 [INFO] distributed.deploy.adaptive: CPU limit exceeded [132485 occupancy / 5 cores]
2018-08-03 08:24:50 [INFO] distributed.deploy.adaptive: Scaling up to 6 workers
```
This is the status of my evicted pod: 
```
"status": {
"message": "The node was low on resource: memory.",
"phase": "Failed",
"reason": "Evicted",
"startTime": "2018-08-05T11:29:55Z"
}
```
It seems to be that failed pods are not excluded in the podlist, only Successful pods are. So `to_create` in `scale_up` ends up being 0.
The simple fix is the one attached, but maybe more changes should be made.
- Should we cleanup failed pods?
- Should …
> Exclude failed pods from list of pods

- dask_kubernetes/core.py
- dask_kubernetes/tests/test_core.py
closes #92
I've taken the minimal distruption path here. Only environment variables in the pod spec are expanded. Two other ways this could be done include:
1. expand environment variables in the config.py module. This would only work for variables set in the dask configuration files, not for the worker spec yaml. This would open up the option of expanding environment variables other than the ones in the pod spec. I don't need this at the moment but it may be worth considering.
1. in the `make_pod_from_dict` function (in objects.py). This would further tie the behavior to just expanding variables to the pod spec, and nothing else.
cc @jacobtomlinson and @mrocklin 
xref: https://github.com/dask/dask/pull/3893
> expand environment variables in pod specs

- dask_kubernetes/core.py
This enables dask_kubernetes to close clusters asynchronously
await cluster.close()
This follows on to https://github.com/dask/distributed/pull/2437
> Pass through return value from close

- doc/source/index.rst
In response to dask/dask-kubernetes#121 I've added a quick start example for using the cluster.
> Add usage example to quickstart

- dask_kubernetes/objects.py
- dask_kubernetes/tests/test_core.py
This is a followup PR to #109 and #110. 
The basic idea is that the prior work only applied the default toleration to `pod_template`s created `make_pod_spec`. This PR moves the existing toleration specifications to `clean_pod_template` to make sure the tolerations are set for all instantiations of `KubeCluster`. 
cc @jacobtomlinson and @yuvipanda
> move default tolerations to clean_pod_template

- dask_kubernetes/objects.py
- dask_kubernetes/tests/test_core.py
At this point, this is for illustration purposes only. It builds on #145 and gives #146 a try. By default, this now creates dask-worker pods with the following affinity and tolerations:
```yaml
spec:
affinity:
nodeAffinity:
preferredDuringSchedulingIgnoredDuringExecution:
- preference:
matchExpressions:
- key: k8s.dask.org/node-purpose
operator: In
values:
- worker
weight: 100
tolerations:
- effect: NoSchedule
key: k8s.dask.org/dedicated
operator: Equal
value: worker
- effect: NoSchedule
key: k8s.dask.org_dedicated
operator: Equal
value: worker
- effect: NoExecute
key: node.kubernetes.io/not-ready
operator: Exists
tolerationSeconds: 300
- effect: NoExecute
key: node.kubernetes.io/unreachable
operator: Exists
tolerationSeconds: 300
```
If my understanding is correct: A kubernetes cluster / …
> Default affinity

- dask_kubernetes/core.py
Fixes #140. Closes #143 
From @jacobtomlinson's PR - It seems to be unnecessary to return the list of pod objects which were created by the scale up operation. It results in a dictionary of pods being blurted into your notebook when calling scale or scale_up.
This PR just fixes a little bug in the logic for `scale_up`.
> Stop scale up from returning pods (continues #143)

- dask_kubernetes/core.py
- dask_kubernetes/logs.py
Add a couple of new log classes which extend `str` and `dict` to add some ipywidgets. This is aimed to make viewing logs easier.
Each log is a string which is rendered as a `<code>` block in an `HTML` widget. Then all logs are a dictionary of the log strings wrapped in an accordion view.
Would appreciate some pointers on testing ipywidgets stuff.
> Add widgets for logs

- dask_kubernetes/tests/test_core.py
Failed locally with 
```pytb
======================================================================== FAILURES =========================================================================___________________________________________________________ test_diagnostics_link_env_variable ____________________________________________________________
pod_spec = {'api_version': None,
'kind': None,
'metadata': {'annotations': None,
'cluster_name': None,
...  'termination_grace_period_seconds': None,
'tolerations': None,
'volumes': None},
'status': None}
loop = <tornado.platform.asyncio.AsyncIOLoop object at 0x1196e86a0>, ns = 'test-dask-kubernetesae2a0756-1'
def test_diagnostics_link_env_variable(pod_spec, loop, ns):
pytest.importorskip("bokeh")
with dask.config.set({"distributed.dashboard.link": …
```
> skip if no ipywidgets

- .circleci/config.yml
- README.rst
- dask_kubernetes/adaptive.py
- dask_kubernetes/core.py
- dask_kubernetes/tests/test_core.py
This is just to check that things work with the current `master` branch of `dask/dask` and `dask/distributed` prior to releasing `2.3.0` upstream. 
I think the CI already runs against upstream `master` branches, so I've included a trivial change to the README to trigger CI
> Prepare for Dask 2.3.0 release

- dask_kubernetes/core.py
- dask_kubernetes/tests/test_async.py
Looks like we lost the ability to specify the scheduler port as part of the #162 rewrite.
This PR reinstates that option and tests for it.
Fixes #195
> Pass port to local scheduler

- doc/source/index.rst
This pull request fixes a bug in the documentation. It seems the fastparquet packet requires gcc, so without `gcc` in `EXTRA_APT_PACKAGES` this error will occur:
```
copying fastparquet/test/test_util.py -> build/lib.linux-x86_64-3.7/fastparquet/test
copying fastparquet/test/test_with_n.py -> build/lib.linux-x86_64-3.7/fastparquet/test
.....
building 'fastparquet.speedups' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/fastparquet
gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.7m -I/opt/conda/lib/python3.7/site-packages/numpy/core/include -c fastparquet/speedups.c -o build/temp.linux-x86_64-3.7/fastparquet/speedups.o
unable to execute 'gcc': …
```
> adding gcc to EXTRA_APT_PACKAGES to fix error

- dask_kubernetes/core.py
- dask_kubernetes/kubernetes.yaml
(partially) fixes #206 
- changes the kwarg `scheduler_timeout` to `idle_timeout` to match the actual behavior of this kwarg
- passes the configuration of this setting to `distributed.yaml`, rather than having a separate value in `kubernetes.yaml`
The question still remains of whether there should be an implementation of the original intended behavior of `scheduler_timeout` (i.e. to timeout after a certain amount of time not having been connected to a client). And, if so, should the pod containing the scheduler also be killed if the scheduler dies.
> WIP: change scheduler_timeout to idle_timeout

- dask_kubernetes/core.py
- dask_kubernetes/kubernetes.yaml
When using cloud providers load balancers (in my case Azure) for the remote scheduler service it takes more than 30 secs for the service to get an IP accessible from outside the cluster.
This PR adds a new setting in the dask-kubernetes yml config file to set this timeout to a given value in seconds.
This is my first PR on the project so this will likely need some extra work.
> Add timeout settings to wait for the remote scheduler service

- dask_kubernetes/core.py
- dask_kubernetes/kubernetes.yaml
- dask_kubernetes/objects.py
This can be usefull when one wants to set different affinities for the
scheduler and the worker pods.
My personal use case is to take advantage of premptible nodes for dask workers but keep the scheduler on a guaranteed node.
Attempts to fix #208.
> Add optional separate scheduler deployment

- dask_kubernetes/core.py
Fixes #213 
It seems like `_` is not a valid character for a pod name. As we are already escaping the name we can just drop this character from our list of valid characters.
> Remove _ from valid characters

- ci/environment-3.7.yml
- dask_kubernetes/core.py
- dask_kubernetes/tests/test_async.py
- dask_kubernetes/tests/test_sync.py
This PR allows the `KubeCluster` to maintain the number of worker pods in adaptive mode, even if pods are lost/deleted externally.
This PR fixes https://github.com/dask/dask-kubernetes/issues/216
`KubeCluster._update_worker_status` was not working correctly. The name found in `KubeCluster.scheduler_info` defaulted to worker address, and was thus different from the corresponding key in `KubeCluster.workers`.
The auto-generated worker name is handled correctly by the `Worker` and is appended to `args` in the Pod spec.
- increas scope of slow test fixtures for faster tests
- remove `tornado` dependency in favour af native `asyncio` as not needed with `python>=3.5`
> Set the name of each worker to allow tracking worker removals.

- Makefile
- dask_kubernetes/core.py
- dask_kubernetes/objects.py
- dask_kubernetes/tests/conftest.py
- dask_kubernetes/tests/test_async.py
- dask_kubernetes/tests/test_sync.py
In an attempt to unblock the CI I'm marking these tests as xfail for now.
It looks like the test below these is also marked as xfail because the async kubernetes library had a problem with setting default config. Now with these tests failing it looks like the main kubernetes library has issues with setting defaut config too.
> Mark tests as xfail to unblock CI

- dask_kubernetes/core.py
- dask_kubernetes/helm.py
- dask_kubernetes/tests/test_async.py
The check for the `helm` command was accidentally at the module level, so it would raise on import of `dask_kubernetes`.
Updated the check so that it happens when `HelmCluster` is instantiated.
Closes #262
> Make the helm command an optional dependency

- dask_kubernetes/objects.py
As we do not use any of the async methods in the `objects` submodule we may not need the `kubernetes_asyncio` client.
This could be a solution for #264 as we are not creating and closing the client in an async way resulting in a warning.
> Use sync client for objects submodule

- Makefile
Fix to #279 .
test-runner-setup.yaml is under ci/ instead of kubernetes/
> Change test-runner-setup.yaml path under make k8s-deploy

- dask_kubernetes/core.py
- dask_kubernetes/tests/test_async.py
- dask_kubernetes/tests/test_sync.py
Add lower() after escaping the username.
This is a fix to #213.
Test method:
```
make test EXTRA_TEST_ARGS='-k escape'
```
> Transform username to lowercase when escaping

- .github/workflows/ci.yaml
Current CI failures appear to be a result of GitHub Actions deprecating some options. This version bump should resolve that.
> Bump kind action version

- dask_kubernetes/core.py
- dask_kubernetes/kubernetes.yaml
- dask_kubernetes/objects.py
- doc/source/kubecluster.rst
Adds PDB creation/deletion for the remote scheduler option within a
`KubeCluster`.
Contributes to dask/dask-kubernetes#282
Signed-off-by: Nick Groszewski <groszewn@gmail.com>
> feat(pdb): Add support for pdb creation for remote scheduler

- dask_kubernetes/core.py
PR resolves #299
This is a little hacky in that we are overwriting the name rather than instantiating a cluster with the generated name.  It's not entirely clear to me how to do this as dask-kubernetes does not directly use Cluster but rather worker/scheduler specs
> Property Name Fixes

- dask_kubernetes/helm.py
This is a small PullRequest to allow user side parametrization of dask scheduler service when NodePort is chosen as its type.
As this is a very minor change, do you require any additional testing and/or documentation? Manually I have been able to connect without an issue with this change.
> add nodehost and nodeport kwargs to HelmCluster init

- .github/workflows/ci.yaml
- ci/Dockerfile
- doc/source/testing.rst
Dask and distributed have renamed their default branch to `main`. Updating the CI pip installs.
> Update CI installs after upstream projects switched to main

- doc/source/kubecluster.rst
Add PDB resource RBAC permissions to the documented permissions for `KubeCluster` management.
Contributes to #313
Signed-off-by: Nick Groszewski <nicholas.groszewski@capitalone.com>
> docs(rbac): Add PDB RBAC permissions to documentation

- dask_kubernetes/core.py
Minor correction to the KubeCluster docstring, which fixes #315
> Minor correction to KubeCluster docstring: deploy_mode defaults to remote

- doc/source/kubecluster.rst
Noticed that the docs showing `Deprecated, please use the KubeCluster constructor directly` [here](https://kubernetes.dask.org/en/latest/kubecluster.html#dask_kubernetes.KubeCluster.from_yaml). There might be other places where issues like this exist, I probably didn't catch them all
> Updated kubecluster to remove depreciated docs

- dask_kubernetes/objects.py
Added `type` argument to `make_pod_spec` function. 
I had an issue using `make_pod_spec` element as `scheduler_pod_template` in `KubeCluster` constructor. My scheduler was unable to start with `ValueError: missing port number in address '$(DASK_SCHEDULER_ADDRESS)'` because `args` list contains elements, that relate to "dask-worker" explicitly.
> Add type argument to make_pod_spec

- dask_kubernetes/core.py
- dask_kubernetes/objects.py
Sorry, I was in a hurry on my previous pull request [#330](https://github.com/dask/dask-kubernetes/pull/330) looking for a solution. There was a laconic fix with deletion of a tabulation. Returned the previous state of `make_pod_spec`.
> Better fix for make_pod_spec ValueError case

- dask_kubernetes/core.py
Thanks very much for this project!
I've started getting familiar with `dask-kubernetes` recently, and found what I believe is a small bug. The teardown method `dask_kubernetes.core.Pod.close()` tries to access details of `self._pod` before checking whether or not `self._pod` is `None`. As a result, if you tear down a `Pod` object that is already empty, you'll get the following error:
> AttributeError: 'NoneType' object has no attribute 'metadata'
This PR proposes a fix to avoid that.
> ensure Pod.close() succeeds when pod has already been removed

- dask_kubernetes/tests/test_objects.py
I've been getting familiar with `dask-kubernetes` recently and wanted to make some small contributions.
I found what looks like a duplicated unit test in `tests/test_objects.py`. There are two tests there named `test_extra_container_config_merge()`, and both seem to be testing the exact same thing.
This PR proposes removing one of the duplicate tests.
I found this by running `mypy --ignore-missing-imports .`, which yielded a few warnings including the following:
> dask_kubernetes/tests/test_objects.py:92: error: Name 'test_extra_container_config_merge' already defined on line 65
I think it would be useful for maintainers here to set up `mypy` in continuous integration in the future, to catch such issues. In this case it doesn't look like there was any loss of testing coverage because …
> [ci] remove duplicate unit test

- dask_kubernetes/objects.py
I ran `pylint dask_kubernetes` today to see if there were any small things I could contribute fixes for, and I think I found some!
This PR proposes changes to fix these two warnings raised by `pylint`.
```text
dask_kubernetes/objects.py:101:25: W0612: Unused variable 'val' (unused-variable)
dask_kubernetes/objects.py:12:4: W0611: Unused import yaml (unused-import)
```
Thanks for your time and consideration.
> remove unused import 'yaml'

- dask_kubernetes/helm.py
This PR proposes removing a statement in the `HelmCluster` constructor which seems to not do anything.
I found this by running `pylint dask_kubernetes/`, which produces the following:
> dask_kubernetes/helm.py:109:8: W0104: Statement seems to have no effect (pointless-statement)
Thanks for your time and consideration.
> remove unnecessary statement in HelmCluster constructor

- dask_kubernetes/__init__.py
Because `__all__` in `__init__.py` is not a list of strings, using `from dask_kubernetes import *` results in an error. This PR changes `__all__` to a list of strings.
I've been getting more familiar with `dask-kubernetes`, and looking for small opportunities to contribute.
Running `pylint dask_kubernetes`, I saw the following significant warning.
```text
dask_kubernetes/__init__.py:14:11: E0604: Invalid object 'KubeCluster' in __all__, must contain only strings (invalid-all-object)
dask_kubernetes/__init__.py:14:24: E0604: Invalid object 'HelmCluster' in __all__, must contain only strings (invalid-all-object)
```
This one is fairly serious. On `main`, running the following
```shell
python setup.py install
python -c 'from dask_kubernetes import *; print(dir())'
```
results in this error: …
> allow imports like 'from dask_kubernetes import *'

- .gitignore
I was looking at this project's `.gitignore` this morning. This PR proposes adding a few additional rules to cover the following:
* additional C/C++ compiled objects (currently only `.so` is ignored)
* archive formats like zip and 7zip
* temporary Jupyter notebooks
* data files
* secrets and key material
Thanks for your time and consideration.
> add secret material to gitignore

- doc/requirements-docs.txt
- doc/source/conf.py
Bumping the minimum docs theme to use the new version. This isn't strictly necessary but I wanted to raise a PR to trigger the rtd preview and check everything looks ok.
xref dask/dask-sphinx-theme#54
> Use new Dask docs theme

- dask_kubernetes/helm.py
- dask_kubernetes/tests/helm/values.yaml
- dask_kubernetes/tests/test_helm.py
A solution to this [issue](https://github.com/dask/dask-kubernetes/issues/385). I added an optional group name to `HelmCluster.scale` method. So now users can scale the additional worker groups that they create based on the worker group name.
> Allow scaling of additional worker groups with HelmCluster (#385)

- doc/source/helmcluster.rst
- doc/source/index.rst
- doc/source/kubecluster.rst
These changes include:
- Directing new users to the main [Dask on Kubernetes](https://docs.dask.org/en/latest/deploying-kubernetes.html) page earlier.
- Adding code examples to the index.
- Simplifying the `KubeCluster` quickstart example.
- Make better use of `:doc:` and `:class:` directives.
> Docs improvements

- dask_kubernetes/objects.py
- doc/source/kubecluster.rst
This is a small docs-only PR that adds a more detailed docstring to `make_pod_spec`. After rooting through the source code for this info a few times over the past year, I thought it would be useful to add to the API section of the docs.
> add detailed docstring to make_pod_spec

- dask_kubernetes/objects.py
- dask_kubernetes/tests/test_objects.py
This adds a new keyword argument to `make_pod_spec`, facilitating passing worker resources through to the `dask-worker --resources` option.
This avoids the pattern of manipulating the pod spec after creating.
Before:
```python
pod_spec = make_pod_spec(...)
pod_spec.spec.containers[0].args.extend(["--resources", "FOO=1"])
```
Now:
```python
pod_spec = make_pod_spec(..., resources="FOO=1")
```
> Pass worker resources to pod args

- dask_kubernetes/core.py
The labels weren't correctly assigned for the pdb which made selecting pdbs belonging to a `KubeCluster` impossible. Functionality is the same as with `_create_service` above.
> Fix label assignment for pdb_template

- dask_kubernetes/operator/tests/test_operator.py
Moving the runner and cluster creation into fixtures made it tricky to make assertions after those things have stopped/been deleted
For the runner I've removed the `with` statement and just instantiated the running with the necessary arguments. That means in the test we need to do the `with` each time.
```python
def test_operator_runs(kopf_runner):
with kopf_runner as runner:
```
I've then applied that same pattern to the `simplecluster` fixture so now instead of applying and deleting the resource during the fixture it yields an async context manager that we can use in a `async with` statement to trigger the applying and deleting when we want to.
```python
@pytest.mark.asyncio
async def test_simplecluster(gen_cluster):
async with gen_cluster() as cluster_name:
```
> Refactor fixtures

- .github/workflows/ci.yaml
- setup.py
Given that folks are still having 3.7 issues in #376 and we are discussing dropping it in dask/community#213 I'm going to drop support here now. Also adding CI to test against 3.9 and 3.10.,
> Drop Python 3.7 and add CI for 3.9 and 3.10

- .github/workflows/ci.yaml
- dask_kubernetes/operator/daskcluster.py
- dask_kubernetes/operator/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/tests/resources/simpleworkergroup.yaml
- dask_kubernetes/operator/tests/test_operator.py
As a part of https://github.com/dask/dask-kubernetes/pull/392, the Dask Operator needs to create/update/delete pods and things on Kubernetes whenever we create our custom resources. This PR is concerned with creating and deleting the worker pods when we create or delete a DaskCluster resource or DaskWorkerGroup resource, respectively.
> Create workers with the Dask Operator

- .github/workflows/ci.yaml
- dask_kubernetes/operator/customresources/daskcluster.yaml
- dask_kubernetes/operator/customresources/daskworkergroup.yaml
- dask_kubernetes/operator/daskcluster.py
- dask_kubernetes/operator/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/tests/resources/simpleworkergroup.yaml
- dask_kubernetes/operator/tests/test_operator.py
As a part of https://github.com/dask/dask-kubernetes/pull/392, the Dask Operator needs to scale workers on Kubernetes whenever we create our DaskWorkerGroup custom resources are modified. This PR is concerned with scaling worker pods (manually) when we change the replicas key in a DaskWorkerGroup resource.
> Add Scaling to the Dask Operator

- .readthedocs.yaml
Since we dropped Python 3.7 in Dask lately and RtD defaults to it this PR manually bumps the version to 3.9.
> Bump Python version in Read the Docs

- dask_kubernetes/operator/deployment/Dockerfile
- dask_kubernetes/operator/deployment/manifest.yaml
Adds some initial packaging for the operator.
First the operator gets wrapped in a container image:
```
$ docker build -t ghcr.io/dask/dask-kubernetes-operator:latest -f dask_kubernetes/operator/deployment/Dockerfile .
```
_For local dev you'll need to push this to your kubernetes cluster, for me on `kind` it meant running `kind load docker-image --name pytest-kind ghcr.io/dask/dask-kubernetes-operator:latest`_
Then to install the operator on Kubernetes you need to apply the example manifest which creates a service account, cluster role, binding and deployment.
```
$ kubectl apply -f dask_kubernetes/operator/deployment/manifest.yaml
```
Now the operator is running and you can create `daskcluster` resources (assuming you have the CRDs installed).
> Add docker image and manifest for deployment

- dask_kubernetes/objects.py
- dask_kubernetes/tests/test_async.py
- Add support for scheduling GPUs ([k8s docs](https://v1-22.docs.kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/)) ref https://github.com/dask/dask-kubernetes/pull/398#issuecomment-1076297582
- Correct `memory_limit` docstring: fractions (float) and 'GB' (str, internally converted to 'GiB') are [supported](https://github.com/dask/distributed/blob/2d3fddc14d1e06fd06b9f0f4c3256f254f3c670e/distributed/worker_memory.py#L344) by `--memory-limit` ([CLI docs](https://docs.dask.org/en/latest/deploying-cli.html)) but not by k8s' Pod resources spec ([k8s docs](https://v1-22.docs.kubernetes.io/docs/concepts/configuration/manage-resources-containers/)). It took me some time to find this out also ref https://github.com/dask/dask/issues/8224
- Sync docstring arg order with the function signature …
> Add gpu_limit to make_pod_spec

- dask_kubernetes/constants.py
- dask_kubernetes/core.py
- dask_kubernetes/objects.py
- dask_kubernetes/tests/test_async.py
- dask_kubernetes/tests/test_objects.py
- dask_kubernetes/tests/test_sync.py
`Pod.logs()` will fail when there are multiple containers within one pod. 
It will fail with e.g: 
```
kubernetes_asyncio.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Audit-Id': '6665d5a7-0ace-40f6-8986-96f9713d1275', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 24 Mar 2022 11:30:43 GMT', 'Content-Length': '249')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod dask-bstadlbauer-5abb6a0e-2s5xvr, choose one of: [vault-agent-init dask-worker vault-agent]","reason":"BadRequest","code":400}
```
This is an issue, as some secret injection frameworks use a sidecar container within the same pod to inject …
> Fix missing container name in `Pod.logs()`

- dask_kubernetes/operator/core.py
- dask_kubernetes/operator/daskcluster.py
- dask_kubernetes/operator/tests/resources/simpleworkergroup.yaml
- dask_kubernetes/operator/tests/test_operator.py
We will re-implement autoscaling later.
> Remove autoscaling

- dask_kubernetes/operator/daskcluster.py
As apart of #392. Since the operator is using a `kubectl` command, we need to check that kubectl is installed.
> Add check for kubectl dependecy in operator

- dask_kubernetes/operator/deployment/Dockerfile
As a part of #392, we want to install `kubectl` in the Docker image.
> Install kubectl for Dask Operator

- dask_kubernetes/operator/daskcluster.py
- dask_kubernetes/operator/deployment/Dockerfile
- Moved the auth stuff into a startup event
- Removed use of `kubectl` in the operator code
- Removed `kubectl` from the docker image
> Remove kubectl dependency from operator

- .github/workflows/release.yml
Adds a step to the release CI that builds the Operator docker image. If it is run on a tag it will also push to GHCR.
> Add operator Docker build and release step

- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/operator/daskcluster.py
- dask_kubernetes/operator/tests/test_operator.py
Start removing all uses of `kubectl` from the new `dask_kubernetes.experimental.KubeCluster` class.
Only one left is scale because I can't figure out what to put in the body of [`patch_namespaced_custom_object_scale`](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#patch_namespaced_custom_object_scale).
> Remove kubectl from dask_kubernetes.experimental.KubeCluster

- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/operator/customresources/daskworkergroup.yaml
- dask_kubernetes/operator/operator.py
- dask_kubernetes/operator/tests/test_operator.py
Closes #449 
- Add `cluster` property to worker groups to make it easier for them to find their own scheduler. 
- Small hygiene tweaks
> Fix worker to scheduler pairing

- dask_kubernetes/operator/operator.py
When a workergroup is created it now patches itself with the ownership pointing to the cluster object in the create hook. This means that additional worker groups will also be correctly owned by the cluster. 
I also removed the pod creation logic from the create hook and just call the update hook instead to reduce duplication.
> Fix worker group adoptions

- dask_kubernetes/core.py
In an interesting edge-case, when you have `user` or `uuid` env variables defines str.format dies because of dupplicate keys. The fix is to filter the environ dictionary and remove those 2 keys
fixes #453 
I was unable to test this locally properly because tests were failing for me when I downloaded the project.
> fix: environ may duplicate keys for str format

- ci/Dockerfile
- dask_kubernetes/operator/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/tests/resources/simpleworkergroup.yaml
Operator tests are using the latest Dask release container but we install `dask` and `distributed` from source in CI so we end up with mismatched environments in the clusters we create in our tests.
We already build a `dask-kubernetes:dev` image for testing to fix this but don't seem to be using it in the operator tests.
This PR updates the operator tests and also sets the CI image to build from gchr.io instead of Docker Hub.
> Fix Docker image name in operator tests

- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/operator/tests/test_operator.py
I've refactored things a little here so that when you create a cluster it checks if one with that name already exists and if so just connects to it.
```python
from dask_kubernetes.experimental import KubeCluster
cluster = KubeCluster(name="foo")
cluster2 = KubeCluster(name="foo")
```
You might not always want this, so you can explicitly set the `create_mode` kwargs to specify if you want create only, connect only or both.
```python
from dask_kubernetes.experimental import KubeCluster, CreateMode
cluster = KubeCluster(name="foo", create_mode=CreateMode.CREATE_ONLY)
```
This also enables us to implement `from_name` for `dask-ctl` compatibility.
```python
from dask_kubernetes.experimental import KubeCluster, CreateMode
cluster = KubeCluster.from_name(name="foo")
cluster = …
```
> Implement from name and connecting to existing clusters

- dask_kubernetes/operator/operator.py
Given that we only call the RPC once right now and we are shifting to the HTTP API soon I decided to simplify things a little and remove the RPC tracking singleton.
This PR just creates the RPC when we need it.
> Only connect the RPC when we need it

- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/operator/tests/test_operator.py
- doc/source/operator.rst
Enabled the `add_worker_group` and `delete_worker_group` methods on `dask_kubernetes.experimental.KubeCluster` and made them a little more configurable.
Also added a test and documentation.
> Enable additional worker groups

- doc/source/operator.rst
Quick fix for a docker image name in the documentation, so the `highmem-worker-group` workers run correctly.
> Fix docker image name in documentation

- doc/source/operator.rst
Follow on from #469. Noticed it uses the old Docker Hub name in a few other places.
> Update all references to ghcr.io

- .pre-commit-config.yaml
- ci/pre-commit-crd.py
We are currently installing the latest dev version of `k8s-crd-resolver` in the pre-commit hooks which could easily break with upstream changes. This PR pins to a specific version which can be changed in the `.pre-commit-config.yaml` config.
It's not perfect but it is a reasonable stopgap while `k8s-crd-resolver` doesn't have pre-commit support.
> Pin k8s-crd-resolver version

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/serviceaccount.yaml
- doc/source/operator.rst
Add the roles/rolebindings to the default service account in the operator helm chart. 
Also added a bit of documentation for using the helm chart. The biggest issue to point out here is the lack of update/delete support for CRDs in helm. Maybe we could also add some doco about default values? What do you reckon?
Related to #479
> feat: add service account roles/rolebinding to operator helm chart

- dask_kubernetes/experimental/kubecluster.py
Closes #484 
Adds a finalizer that reaps clusters that have `shutdown_on_close` set to `True` (the default).
> Add finalizer to reap clusters when Python exits

- .github/workflows/operator.yaml
- ci/install-deps.sh
- dask_kubernetes/conftest.py
- dask_kubernetes/operator/operator.py
In #488 I am working on getting Dask clusters created by the operator to play nicely with Istio. So far this has been more challenging than I expected.
This PR is intended as a stop-gap which adds Istio to the CI but adds labels to the scheduler and worker pods to disable sidecar injection. This should mean the operator will work on clusters running Istio, but without the benefit of actually using it.
Hopefully, these changes will be quickly replaced by efforts in #488.
xref #482
> Disable istio sidecar injection

- dask_kubernetes/classic/tests/test_async.py
- dask_kubernetes/conftest.py
- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/experimental/tests/test_kubecluster.py
- dask_kubernetes/helm/helmcluster.py
- dask_kubernetes/helm/tests/test_helm.py
- dask_kubernetes/operator/tests/test_operator.py
- requirements-test.txt
- setup.cfg
see also https://github.com/dask/distributed/issues/6163
> support running experimental KubeClusters and HelmClusters on the same loop as another SyncMethodMixin instance

- .github/workflows/release.yml
- dask_kubernetes/operator/deployment/helm/chartpress.yaml
Fixes #491 
I'm a little hesitant to make this change as the Helm Chart in the repo is a secondary install method so it seems like bad separation of concerns. But as @consideRatio points out just because `chartpress` builds the Docker image it doesn't mean we can't use it without the Helm Chart.
Chartpress now handles building the Docker image for the operator. The CI also now runs chartpress on every run but adds the `--force-push --force-publish-chart` flags on tags so we can continue testing the Docker image build on every run.
@consideRatio would you mind reviewing?
> Delegate Docker Image building to chartpress

- dask_kubernetes/kubernetes.yaml
- doc/source/kubecluster.rst
xref #498 
Looks like the container name has to be `dask-worker` so updating the example to reflect that.
> Update examples with correct container name

- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/operator/operator.py
- dask_kubernetes/operator/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/tests/resources/simpleworkergroup.yaml
Rather than passing the scheduler address via the pod args (and requiring all folks writing YAML manifests to do the same) this PR injects the `DASK_SCHEDULER_ADDRESS` as an env var in all worker pod containers.
This is a step towards removing boilerplate from the YAML xref #474
> Set scheduler address in injected environment variable

- dask_kubernetes/common/networking.py
- dask_kubernetes/operator/operator.py
This PR replaces the call to the RPC object in favor of the new scheduler HTTP API. 
Related Issue: [#5935](https://github.com/dask/distributed/issues/5935)
Related PR: [#6270](https://github.com/dask/distributed/pull/6270)
> Replace RPC with Scheduler HTTP API

- ci/pre-commit-crd.py
- dask_kubernetes/conftest.py
- dask_kubernetes/operator/customresources/daskcluster.yaml
- dask_kubernetes/operator/customresources/daskjob.patch.yaml
- dask_kubernetes/operator/customresources/daskjob.yaml
- dask_kubernetes/operator/customresources/templates.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskcluster.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskjob.yaml
- dask_kubernetes/operator/deployment/manifests/daskcluster.yaml
- dask_kubernetes/operator/deployment/manifests/daskjob.yaml
- dask_kubernetes/operator/operator.py
- dask_kubernetes/operator/tests/resources/simplejob.yaml
- dask_kubernetes/operator/tests/test_operator.py
- doc/requirements-docs.txt
- doc/source/conf.py
- doc/source/index.rst
- doc/source/operator.rst
- doc/source/operator_installation.rst
- doc/source/operator_kubecluster.rst
- doc/source/operator_resources.rst
Closes #483.
Implements a `DaskJob` resource which is a batch style resource that creates a `Pod` to perform some specific task from start to finish alongside a `DaskCluster` that can be leveraged to perform the work.
Once the job `Pod` runs to completion the cluster is removed automatically to save resources. This is great for workflows like training a distributed machine learning model with Dask.
```mermaid
graph TD
DaskJob(DaskJob)
DaskCluster(DaskCluster)
SchedulerService(Scheduler Service)
SchedulerPod(Scheduler Pod)
DaskWorkerGroup(Default DaskWorkerGroup)
WorkerPodA(Worker Pod A)
WorkerPodB(Worker Pod B)
WorkerPodC(Worker Pod C)
JobPod(Job Runner Pod)
DaskJob --> DaskCluster
DaskJob --> JobPod
DaskCluster --> SchedulerService
SchedulerService --> SchedulerPod
DaskCluster --> …
```
> Add DaskJob resource

- dask_kubernetes/classic/tests/test_sync.py
- dask_kubernetes/common/networking.py
- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/kubernetes.yaml
- dask_kubernetes/operator/deployment/manifests/operator.yaml
- dask_kubernetes/operator/operator.py
- dask_kubernetes/operator/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/tests/resources/simplejob.yaml
- doc/source/operator_installation.rst
- doc/source/operator_resources.rst
- Correctly detects the current namespace when run within the Kubernetes cluster.
- Use `dask-operator` namespace for the operator service instead of `kube-system`.
- Document enabling Kubeflow users to create Dask CRD resources.
- Have the scheduler listen on all addresses to enable service to work.
- Plays nicely with the notebook Istio/Envoy egress by renaming ports (and maybe unblocks #488 🎉).
- Doesn't port forward the dashboard if running in-cluster.
> Small fixes to get things working on Kubeflow

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/serviceaccount.yaml
- dask_kubernetes/operator/deployment/manifests/operator.yaml
The operator is unable to watch `daskjob` resources. Updating cluster role.
> Fix operator daskjob permissions

- dask_kubernetes/classic/kubecluster.py
Closes #517.
In #509 we fixed the dashboard port forwarding in `experimental.KubeCluster` when running from within the Kubernetes cluster. This PR adds the same fix to `classic.KubeCluster`.
cc @mmccarty
> Fix dashboard forwarding

- dask_kubernetes/operator/deployment/helm/chartpress.yaml
Fixes #518 
When the helm chart is published it will now update the image tag in the `values.yaml`.
> Get chartpress to update image tag

- ci/install-deps.sh
- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/experimental/tests/test_kubecluster.py
Allow users to set a custom worker command in `dask_kubernetes.experimental.KubeCluster`.
```python
cluster = KubeCluster(name="customworkercommand",
worker_command=["python", "-m", "distributed.cli.dask_worker"])
```
Closes #537
> Allow custom worker command

- dask_kubernetes/operator/deployment/manifests/operator.yaml
Scale management breaks for a role due to a lack of permissions.
Also guys, could you please cut new release afterwards. There is a serious bug related to `self.name=name` fix in the current one (dask-kubernetes=2022.5.2).
> Allow workergroups scaling

- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/experimental/tests/test_kubecluster.py
- dask_kubernetes/operator/customresources/templates.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskcluster.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskjob.yaml
- dask_kubernetes/operator/deployment/manifests/daskcluster.yaml
- dask_kubernetes/operator/deployment/manifests/daskjob.yaml
- dask_kubernetes/operator/operator.py
- dask_kubernetes/operator/tests/test_operator.py
Closes  #490.
I've added a `status.phase` property to the `DaskCluster` resource and implemented two statuses `Created` and `Running`.
I've updated the controller so that the creation event on `DaskCluster` resources just sets the phase to `Created`. I've then created another hook that watches for that phase being set which then creates the downstream resources, once they have been created the phase is updated to `Running`.
Then the `experimental.KubeCluster` now has a `_wait_for_operator` method that watches for this `status.phase` property. If this doesn't get set after 60 seconds (configurable) the cluster creation will time out because the operator controller is likely not running or in a failed state. This is great because currently, the class will just hang if the controller isn't …
> Add a status to DaskCluster resources and use that to timeout the KubeCluster

- dask_kubernetes/experimental/__init__.py
- dask_kubernetes/experimental/kubecluster.py
- dask_kubernetes/experimental/tests/test_kubecluster.py
- dask_kubernetes/operator/operator.py
- dask_kubernetes/operator/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/tests/resources/simplejob.yaml
- dask_kubernetes/operator/tests/resources/simpleworkergroup.yaml
- dask_kubernetes/operator/tests/test_operator.py
- doc/source/operator_kubecluster.rst
- doc/source/operator_resources.rst
Closes #475 
Closes #544 
The `KubeCluster` class can take a selection of keyword arguments to make it quick and easy to get started, however the underlying `DaskCluster` resource can be much more complex and configured in many ways.
Rather than exposing every possibility via keyword arguments instead, you can pass a valid `DaskCluster` resource spec which will be used when creating the cluster.
You can also generate a spec with `make_cluster_spec` which `KubeCluster` uses internally and then modify it with your custom options.
```python
from dask_kubernetes.experimental import KubeCluster, make_cluster_spec
config = {
"name": "foo",
"n_workers": 2,
"resources":{"requests": {"memory": "2Gi"}, "limits": {"memory": "64Gi"}}
}
cluster = KubeCluster(**config)
cluster = …
```
> Enable passing custom specs

- dask_kubernetes/classic/kubecluster.py
Fixes #548.
@jacobtomlinson it seemed like the less risky approach here was to just set that same port variable; skipping the setter or using `None` felt like it would likely cause problems downstream.
> Don't try to forward dashboard in local mode

- .pre-commit-config.yaml
- ci/pre-commit-crd.py
- requirements-test.txt
We use `k8s-crd-resolver` during the build process to generate k8s CRDs from templates. This happens in CI and also via `pre-commit` to keep the generated files in version control.
It looks like there is a dependency conflict where `k8s-crd-resolver` depends on `prance` which in turn depends on `openapi-spec-validator`. However, the `0.5.0` release of `openapi-spec-validator` has broken `prance`.
To resolve this in the short term I've forked `k8s-crd-resolver` and pinned the version of `openapi-spec-validator` to `<0.5.0`. xref https://github.com/elemental-lf/k8s-crd-resolver/pull/2
This PR switches `dask-kubernetes` to use my fork of `k8s-crd-resolver` for now. Once a new release of `prance` is available this can be reverted.
> Workaround for k8s-crd-resolver dependency issue

- .github/workflows/helmcluster.yaml
- .github/workflows/kubecluster.yaml
- .github/workflows/operator.yaml
- README.rst
- dask_kubernetes/classic/kubecluster.py
- dask_kubernetes/common/objects.py
- dask_kubernetes/kubernetes.yaml
- doc/source/index.rst
- Updated CI to test against Kubernetes v1.25
- Updated README and docs badges
- `PodDisruptionBudget` no longer available in beta namespace with v1.25
> Add Kubernetes v1.25 support

- .github/workflows/helmcluster.yaml
- .github/workflows/kubecluster.yaml
- .github/workflows/operator.yaml
Follow up to #556. Reduces the test matrix to something a little more manageable.
- Stop testing **all** supported Python versions against **all** supported Kubernetes versions
- Test **all** supported Python versions against **latest** Kubernetes
- Test **all** supported Kubernetes versions against **latest** Python
Reduces the number of jobs from `p * k` to `p + k - 1`.
> Only test older k8s versions agianst latest Python

- dask_kubernetes/classic/kubecluster.py
Based on contexts, it should be "deleted" instead of "deleated"
> Fix potential typo in kubecluster.py

- dask_kubernetes/kubernetes.yaml
Looks like a quote got dropped which breaks the default config. I expect the unit tests always set this option explicitly so it got missed.
> Fix docker image default config value

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/serviceaccount.yaml
This PR adds the `daskautoscalers` resource in the `clusterrole` rules.
Without it, the `dask-operator` pod fail to start with the error:
```
[2022-10-12 17:46:55,501] kopf._core.reactor.o [ERROR   ] Watcher for daskautoscalers.v1.kubernetes.dask.org@none has failed: ('daskautoscalers.kubernetes.dask.org is forbidden: User "system:serviceaccount:dask:dask-kubernetes-operator" cannot list resource "daskautoscalers" in API group "kubernetes.dask.org" at the cluster scope')
```
> Add daskautoscalers in the cluster role rules

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/controller/tests/resources/simplejob.yaml
- dask_kubernetes/operator/controller/tests/test_controller.py
- doc/source/operator.rst
As described in https://github.com/dask/dask-kubernetes/issues/571, it would be nice if there was a possibility to add annotations to `dask`-related pods.
This PR adds this capability by: 
- Passing on all annotations set on the `DaskCluster` CR to the scheduler `Pod` as well as the `DaskWorkerGroup` CR
- Passing on all annotations set on the `DaskWorkerGroup` CR to the worker `Pod`s
- Passing on all annotation set on the `DaskJob` CR to the job-runner `Pod`
A small issue I've noticed when implementing this was that there are already some "default" `kopf` and kubernetes related annotations on resources, which I've chosen to ignore: 
-   "kopf.zalando.org/last-handled-configuration"
-   "kubectl.kubernetes.io/last-applied-configuration"
Feel free to suggest alternatives, happy to change …
> Pass on annotations from dask custom resources

- dask_kubernetes/operator/kubecluster/kubecluster.py
The `DaskCluster` doesn't need the `cluster` key to be set in the worker spec. Only the `DaskWorkerGroup` needs that.
By including it the spec generated by `make_cluster_spec` actually fails validation with kubectl.
```console
$ python -c "import yaml; from dask_kubernetes.operator import make_cluster_spec; print(yaml.dump(make_cluster_spec(name='test')))" | kubectl apply -f -        
error: error validating "STDIN": error validating data: ValidationError(DaskCluster.spec.worker): unknown field "cluster" in org.dask.kubernetes.v1.DaskCluster.spec.worker; if you choose to ignore these errors, turn validation off with --validate=false
```
Removing it from `make_worker_spec` and explicitly adding it in the `add_worker_group` call.
> Remove uneccessary cluster key

- dask_kubernetes/operator/deployment/manifests/operator.yaml
Looks like `operator.yaml` was missing the `daskautoscalers` permission. This PR adds it :)
> Add missing `daskautoscalers` permission

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/resources/failedjob.yaml
- dask_kubernetes/operator/controller/tests/test_controller.py
- dask_kubernetes/operator/customresources/daskjob.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskjob.yaml
- dask_kubernetes/operator/deployment/manifests/daskjob.yaml
This PR aims at adding some `status` information to the `DaskJob` CRD.
In particular it adds the following fields to `status`: 
- `jobStatus`: Status of the job. string, required. Can by any of: 
- `JobCreated`: Job CR was created
- `ClusterCreated`: The `DaskCluster` CR associated with the job has been created
- `Running`: The job-runner pod is in "Running" state
- `Successful`: The job-runner pod is in `Succeeded` state
- `Failed`: The job-runner pod is in the `Failed` statue
- `clusterName`: Name of the `DaskCluster` resorce to be created (string)
- `jobRunnerPodName`: The name of the job-runner pod
- `startTime`: Time when the job-runner pod started running
- `endTime`: Time when the job-runner pod went into the `Succeeded` state
@jacobtomlinson: Happy to change any of the stated/the …
> Add status to dask job

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/serviceaccount.yaml
When working on the Flyte `dask` plugin, I've noticed that the operator does not have permissions to change `daskjobs/status`, this adds the missing permission. 
Sorry for not checking this.
> Add missing `daskjobs/status` permissions

- doc/source/operator_installation.rst
I finally managed to get my head around how to append something to a list instead of overwriting it when using `kubectl patch`. This PR updates the docs to use this technique instead of using `kubectl edit` and doing it interactively.
Turns out setting `kubectl patch --type="json" ...` allows you to use [JSON patch syntax](https://jsonpatch.com/) which is neat!
> Document using inline JSON patch to update Kubeflow permissions

- doc/source/index.rst
- doc/source/kubecluster_migrating.rst
- doc/source/operator_installation.rst
Updated the general `helm install` commands with better console output for the `helm repo add` and `helm repo update` commands as well as adding some quality of life flags to the `helm install` like `--create-namespace` and `--generate-name`.
```console
$ helm repo add dask https://helm.dask.org
"dask" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "dask" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm install --create-namespace -n dask-operator --generate-name dask/dask-kubernetes-operator
NAME: dask-kubernetes-operator-1666875935
NAMESPACE: dask-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Operator has been installed successfully.
```
Also updated …
> Improve operator helm install commands

- dask_kubernetes/common/networking.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
This fixes #566.  
I also thread the `port_forward_cluster_ip` KubeCluster argument through to `get_external_address_for_scheduler_service` in order to match the behavior more closely to what I believe the intention is in the [docs](https://kubernetes.dask.org/en/latest/operator_kubecluster.html#dask_kubernetes.operator.KubeCluster).  If my interpretation or implementation here is incorrect, I am happy to correct it. I found it to be important for fast connectivity to remote clusters.  Before, we needed to wait for it to timeout (10s) before port forwarding the service and connecting remotely.
> Connectivity fixes

- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
The `test_multiple_clusters_simultaneously_same_loop` is flaky and hangs around 10% of the time. Skipping it for now to get CI back into a good state.
> Skip flaky test_multiple_clusters_simultaneously_same_loop test

- .github/workflows/operator.yaml
Uses helm to lint the chart and pluto to check operator install manifests for deprecated versions.
https://github.com/FairwindsOps/pluto
- Checks out code
- Runs `helm lint`
- Uses `helm` to generate a static manifest
- Runs `pluto` on the manifest
> Add linting for operator Helm Chart

- .github/workflows/helmcluster.yaml
- .github/workflows/kubecluster.yaml
- .github/workflows/operator.yaml
Use [concurrency groups](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) to cancel in-progress builds when new commits are pushed to PRs.
> Cancel in-progress CI builds on new commit

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
The controller should not change the phase to Running until the LoadBalancer service is truly ready.
This requires the client to also check for actual value of the phase in the status.
> Wait for LoadBalancer service readiness

- .github/workflows/operator.yaml
- dask_kubernetes/conftest.py
- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/test_controller.py
- doc/source/operator_extending.rst
- Switch to using fully qualified resource names everywhere so that we don't collide with similarly named resources in dask-gateway.
- Install dask-gateway as a pytest session fixture so we ensure that all tests pass with gateway installed.
Closes #618
> Ensure the operator can coexist with dask-gateway

- .pre-commit-config.yaml
Looks like `flake8` migrated to GitHub and deleted their GitLab repo so many pre-commit configs are broken. Fixing it here.
> Fix pre commit flake8 config

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/deployment/Dockerfile
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/deployment.yaml
xref #620 
Enabled the `kopf` liveness probe so that k8s can monitor controller health.
> Configure liveness probe for operator controller

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/test_controller.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
Instead of waiting for the service within the cluster creation handler we handle the service status updates directly and only move the cluster into `Running` state if the service is up.
> Handle cluster service status via the scheduler service status

- requirements.txt
#627 was incorrect.  I failed to recognize that this is the outdated/unsupported package.  What we want is `pykube-ng`.  It is currently installed via one of the test deps but we need it in the baseline for recent changes to the controller (see #620).
> Adds `pykube-ng` dep, removes `pykube` dep

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/resources/simplecluster.yaml
- dask_kubernetes/operator/controller/tests/test_controller.py
- Sets the dask workergroup owner during its creation instead of during `daskworkergroup_create` kopf call
- This allows labels to propagate correctly from the dask workergroup to the dask worker pod
closes #623
> set dask workergroup owner during creation

- dask_kubernetes/operator/kubecluster/kubecluster.py
```python
f"Cluster {self.name} doesn't and create mode is '{CreateMode.CONNECT_ONLY}'"
```
to 
```python
f"Cluster {self.name} doesn't already exist and create mode is '{CreateMode.CONNECT_ONLY}'"
```
> Fix typo in error message when connecting to existing `KubeCluster`

- dask_kubernetes/operator/controller/controller.py
In #633 we are seeing a problem where the workers are thrashing when adaptively scaling.
I **think** the problem is that when the scheduler changes the desired number of workers it begins releasing worker processes which put the pod into a `Terminating` state. When the controller catches up on the next cycle it adjusts the desired number of workers which triggers a scale down. When scaling down the `Terminating` pods are included in the count of current pods which results in an over count and the controller attempts to scale down further by removing more pods. 
This means we scale lower than we should.
This PR excludes `Terminating` pods from the count. Testing locally shows things scaling correctly.
> Don't include Terminating pods in scale down calculations

- .gitignore
- dask_kubernetes/operator/kubecluster/kubecluster.py
- dask_kubernetes/operator/kubecluster/tests/conftest.py
- dask_kubernetes/operator/kubecluster/tests/test_discovery.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
This PR adds support to automatically start an `operator.KubeCluster` when created with the `asynchronous` parameter set to `True`.
- Closes #598
> Start the cluster operator.KubeCluster when created asynchronously

- dask_kubernetes/common/networking.py
- dask_kubernetes/operator/controller/controller.py
Closes #637 
Add a slimmed-down service address discovery method for use only inside the k8s cluster. Updated the operator controller to use this.
> Ensure the controller only uses the internal address for the scheduler

- dask_kubernetes/classic/kubecluster.py
- dask_kubernetes/classic/tests/test_sync.py
This PR keeps copies of Pod templates for workers and/or schedulers when they are provided instead of references.
When keeping a reference to a Pod template spec outside of the `classic.KubeCluster` class, those external references could be updated if provided as `pod_template` or `scheduler_pod_template` args.
For example, this [line](https://github.com/dask/dask-kubernetes/blob/a24a3f9284043248e94816432abb9ece8e9be746/dask_kubernetes/classic/kubecluster.py#L584) updates an external reference of `pod_template.spec.containers[0].args[0]` to `dask-scheduler` because we have:
- [self.scheduler_pod_template that references base_pod_template](https://github.com/dask/dask-kubernetes/blob/a24a3f9284043248e94816432abb9ece8e9be746/dask_kubernetes/classic/kubecluster.py#L583)
- [base_pod_template …
> Fix pod templates external references updates

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/serviceaccount.yaml
This PR adds the missing `services/status` role in the `ClusterRole` resource to avoid errors like the following:
```
User "system:serviceaccount:dask:dask-kubernetes-operator" cannot patch resource "services/status" in API group ""
```
> Add services/status in the ClusterRole

- dask_kubernetes/operator/deployment/Dockerfile
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/deployment.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
Adds the ability to provide kopf CLI arguments via the Helm values.yaml file.  
Some callouts:
- I split the container `CMD` out into an `ENTRYPOINT` and `CMD` to make the `args` definition cleaner (allows consumers to just specify CLI args there and not worry about properly starting up container) 
- I kept the container default args the same for backwards compatibility and opted to override the default args via the helm chart
- I've updated the default helm deploy to remove the `--verbose` flag
- I've left the `--all-namespaces` flag as a `CMD` flag, so if users override this they'll need to include the `--all-namespaces` flag again.  I figure this provides the most flexibility (if we hard code it like we do liveness probe users can't change it because its a boolean flag).
- I tested …
> Add support for kopf CLI arguments in operator deployment

- dask_kubernetes/common/networking.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
While working on #658 I noticed a couple of things around creating clusters that I wanted to break out into a separate PR.
- The `_is_service_available` method was sync but was being called in a coroutine. Updated it to be async.
- The default readiness probe waits unnecessarily long before checking the scheduler.
Both of these changes should improve cluster creation time and responsiveness.
> Improve cluster create delays

- dask_kubernetes/common/networking.py
- dask_kubernetes/exceptions.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
Fixes #655 
- Rewritten `wait_for_scheduler` to use `dask_kubernete.aiopykube`.
- Updated `resource_timeout` kwarg docstring to allow reuse in other places.
- Created some new exceptions.
- If the scheduler Pod enters a `CrashLoopBackOff` phase for more than `resource_timeout` we raise and clean up the cluster.
- The exception is caught when creating the cluster and reraised with the scheduler Pod logs.
```python
In [2]: from dask_kubernetes.operator import KubeCluster, make_cluster_spec
...: spec = make_cluster_spec(name="foo", n_workers= 1)
...: spec['spec']['scheduler']['spec']['containers'][0]['args'][0] = "dask-schmeduler"
...: cluster = KubeCluster(custom_cluster_spec=spec)
---------------------------------------------------------------------------
CrashLoopBackOffError …
```
> Raise SchedulerStartupError exception on scheduler CrashLoopBackOff during cluster creation

- doc/source/index.rst
In https://github.com/dask/dask/pull/9912, the organization of links for deploying options in [Deploy Dask Clusters](https://docs.dask.org/en/stable/deploying.html) was improved and we discussed linking to this central page in other projects.
cc @jacobtomlinson @gjoseph92
> Link to central deploying Dask page

- dask_kubernetes/operator/__init__.py
- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
This PR is part of a two part set (#649 is the companion PR) that smooths out the autoscaling logic to reduce thrashing and hopefully smooth out autoscaling actions.   I've duplicated some of the context in both PRs so in case there are different reviewers. 
We've been using the dask operator for some long running workloads and have noticed that the autoscaling logic can result in thrashing in some of our workloads.  When this happened our we either experienced:
- A cluster left in an inconsistent state (no workers but work to be done and no actions to scale up being performed)
- Workers being spun up only to spin down, resulting in excessive data transfers and loss of work when the data could not be transferred within the pod termination grace period.
The second PR fixes a race condition …
> Add cool down period for autoscaling to reduce thrashing

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/clusterrolebinding.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/role.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/rolebinding.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
- doc/source/operator_installation.rst
Users can choose to set `rbac.cluster=false` to create a `Role` instead of a `ClusterRole` and `kopfArgs="{--namespace=my-namespace}"` to ensure the controller only watches that namespace.
```
$ helm install -n my-namespace --generate-name dask/dask-kubernetes-operator --set rbac.cluster=false --set kopfArgs="{--namespace=my-namespace}"
NAME: dask-kubernetes-operator-1749875935
NAMESPACE: my-namespace
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Operator has been installed successfully.
```
> Add the ability to install the operator controller into a single namespace

- doc/source/operator_kubecluster.rst
You can get the Dask Scheduler to run Jupyter on the same port as the Dashboard. Instead of navigating to `/status` you can open `/jupyter/lab`. Adding a little example of doing this to the docs here.
```python
from dask_kubernetes.operator import KubeCluster, make_cluster_spec
spec = make_cluster_spec(name="jupyter-example", n_workers=2, env={"EXTRA_PIP_PACKAGES": "jupyterlab"})
spec["spec"]["scheduler"]["spec"]["containers"][0]["args"].append("--jupyter")
cluster = KubeCluster(custom_cluster_spec=spec)
```
> Add Jupyter example to customizing cluster section

- LICENSE
Updated the license year to 2023 and added "Dask Developers" and "NVIDIA" to the list of copyright holders.
xref https://github.com/dask/community/issues/313
cc @yuvipanda
> Update LICENSE for 2023

- dask_kubernetes/operator/controller/controller.py
`dask.compatibility.entry_points` was deprecated in https://github.com/dask/dask/pull/10113. The whole of `dask.compatibility` is also [not intended to be used outside of `dask`](https://github.com/dask/dask/pull/10113#pullrequestreview-1354876683). Updating here to use `importlib_metadata` directly.
> Remove deprecated dask.compatibility.entry_points

- dask_kubernetes/cli/__init__.py
- dask_kubernetes/cli/cli.py
- setup.py
Added a small CLI utility that hooks into the `dask` CLI extension API. This allows us to extend the `dask kubernetes` CLI and add useful things.
The first useful thing is a command to generate the same `DaskCluster` YAML that `KubeCluster` does under the hood.
```console
$ dask kubernetes gen cluster --name foo                                      
apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
name: foo
spec:
scheduler:
service:
ports:
- name: tcp-comm
port: 8786
protocol: TCP
targetPort: tcp-comm
- name: http-dashboard
port: 8787
protocol: TCP
targetPort: http-dashboard
selector:
dask.org/cluster-name: foo
dask.org/component: scheduler
type: ClusterIP
spec:
containers:
- args:
- dask-scheduler
- --host
- 0.0.0.0
env: []
image: ghcr.io/dask/dask:latest
livenessProbe: …
```
> Add CLI utilities

- dask_kubernetes/cli/cli.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
One of the improvements that the operator has vs the classic dask-kubernetes is that you can create Dask clusters via `kubectl` if you would prefer.
In #712 I added a small CLI utility which allows you to generate the YAML resource that `KubeCluster` does and print it out, this can then be piped into `kubectl`.
```console
$ dask kubernetes gen cluster --name foo | kubectl apply -f -
daskcluster.kubernetes.dask.org/foo created
```
The downside of doing this is that you don't get the nice value-add features that `KubeCluster` provides such as automatic port-forwarding.
This PR adds another utility to make it quick and easy to port-forward both the scheduler and dashboard.
```console
$ dask kubernetes port-forward foo
Scheduler at: tcp://localhost:50429
Dashboard at: …
```
> Add port-forward CLI utility

- dask_kubernetes/operator/kubecluster/kubecluster.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
Fixes: https://github.com/dask/dask-kubernetes/issues/698
Tasks
> Add correct handling for invalid `KubeCluster` kwargs

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/test_controller.py
Closes #636. This PR adds another handler that scales the default worker group when the `worker.replicas` field of the cluster spec is changed.
> Scale Dask worker group from Cluster spec

- dask_kubernetes/operator/kubecluster/kubecluster.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
I noticed that the scheduler_info is not updated accross all cluster instances. So if you scale one `KubeCluster` instance, the other instances will not show the new number of workers. This PR updates all instances of `KubeCluster.scheduler_info` when it's scaled.
> Update scheduler_info across cluster instances

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/customresources/templates.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskcluster.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/crds/daskjob.yaml
- dask_kubernetes/operator/kubecluster/kubecluster.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
Adds an optional `idleTimeout ` config option to the `DaskCluster` spec which instructs the controller to delete idle clusters after a certain timeout.
```yaml
apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
name: foo
spec:
idleTimeout: 60
scheduler:
...
worker:
...
```
Exposed via the Python API as the `idle_timeout` kwarg.
```python
from dask_kubernetes.operator import KubeCluster
cluster = KubeCluster(name="foo", n_workers=1, idle_timeout=60)
```
In the above examples if the scheduler is idle for more than 60 seconds the `DaskCluster` resource will be deleted automatically by the controller. This is regardless of whether the `KubeCluster` object still exists in Python.
~There is a challenge with this implementation which means I don't want to merge it in its current …
> Auto shutdown idle clusters

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/objects.py
In #721 objects for the CRDs were added to the controller. We probably want to reuse those in more places so it might make sense for them to live in their own submodule.
This PR creates `dask_kubernetes.operator.objects` to hold these class definitions.
> Move kr8s objects into separate submodule for better reuse

- dask_kubernetes/operator/kubecluster/kubecluster.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
> KubeCluster.shutdown_on_close should be False when created from_name

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/test_controller.py
Closes #603. Currently, if worker group loses a pod, isn't recreated by the operator. This PR solves that problem by create deployment for each worker. The deployment then creates the worker pod. The advantage of a deployment is that we can define the number of replicas (1 replica/scheduler in this case) and Kubernetes will recreate the worker pod.
> Create worker pods through Deployments

- dask_kubernetes/operator/controller/tests/test_controller.py
- dask_kubernetes/operator/objects.py
Added some useful utility methods to the kr8s `APIObject` subclasses we have in `dask_kubernetes.operator.objects`.
For example if you have a `DaskCluster` object you can quickly get a `Pod` object for the scheduler Pod.
```python
import asyncio
from dask_kubernetes.operator.objects import DaskCluster
async def main():
cluster = await DaskCluster.get("foo")
scheduler_pod = await cluster.scheduler_pod()
if __name__ == "__main__":
asyncio.run(main())
```
Added methods are:
- `DaskCluster.worker_groups()`
- `DaskCluster.scheduler_pod()`
- `DaskCluster.scheduler_deployment()`
- `DaskCluster.scheduler_service()`
- `DaskWorkerGroup.pods()`
- `DaskWorkerGroup.deployments()`
- `DaskWorkerGroup.cluster()`
- `DaskAutoscaler.cluster()`
- `DaskJob.cluster()`
- `DaskJob.pod()`
> Add utility methods to kr8s objects

- doc/source/index.rst
Whoops looks like the docs index page Kubernetes versions badge didn't get updated in #718.
> Update supported k8s versions badge in docs

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/clusterrole.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/role.yaml
This should fix #749 
@jacobtomlinson I've tested this on a fresh k8s cluster where I've helm-installed the operator.
The deployment for the scheduler has been created after I've added the permissions, however, once the scheduler started running I've seen the following exception: 
```
[2023-06-28 09:51:39,162] kopf.objects         [ERROR   ] [dask-ns/my-dask-cluster-scheduler] Handler 'handle_scheduler_service_status/status' failed with an exception. Will retry.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
result = await invoke_handler(
File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
result = await invocation.invoke(
File …
```
> Add `deployments` permission to role and clusterrole

- dask_kubernetes/operator/controller/controller.py
Replaced the first Kubernetes API call to get the `DaskCluster` spec with `kr8s`. Then replaced the second call with using the `kopf` (modifications to the `patch` kwarg get synced back to Kubernetes once the handler exits).
Should functionally have no change.
> Replace kubernetes_asyncio in daskautoscaler_create

- dask_kubernetes/operator/_objects.py
- dask_kubernetes/operator/controller/controller.py
- requirements.txt
Updated the autoscaler adaptive code with `kr8s`. Also bumped `kr8s` to 0.7.0 to benefit from some of the syntactic sugar it added.
> Replace kubernetes_asyncio with kr8s 0.7.0 in daskautoscaler_adapt

- dask_kubernetes/operator/controller/controller.py
Replace `kubernetes_asyncio` with `kr8s` in `daskcluster_default_worker_group_replica_update`. Should functionally have no change.
> Update daskcluster_default_worker_group_replica_update to use kr8s

- .github/workflows/helmcluster.yaml
- .github/workflows/kubecluster.yaml
- .github/workflows/operator.yaml
- setup.cfg
We are seeing lots of cancelled CI runs because tests are rerunning and taking a while to time out. This PR reduces the timeout and instructs `pytest-timeout` to not include fixtures in the timeout (so the initial creation of the `kind` cluster doesn't get timed out).
> Try and reduce timeouts to improve CI time-to-failure

- dask_kubernetes/operator/controller/controller.py
Replace `kubernetes_asyncio` with `kr8s` in all `DaskJob` state transitions. Should functionally have no change.
> Update DaskJob state transitions to use kr8s

- dask_kubernetes/kubernetes.yaml
- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/test_controller.py
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/deployment.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
Closes #733. This PR adds provides the ability for the operator deploy workers in batches of a given `size` with a cooldown `delay` between deployments.
> Add batch worker provisioning capability to the Operator

- dask_kubernetes/operator/_objects.py
- dask_kubernetes/operator/controller/controller.py
- requirements.txt
`kr8s` 0.8.5 supports objects adopting other objects. This PR switches the autoscaler adoption to use kr8s to make the code a little more readable. This is also a bit of a test run before using it in other places.
> Change autoscaler adoption to use kr8s

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
We've just tried to deploy the `2022.7.0` version of the helm chart and ran into: 
```
Handler 'daskworkergroup_replica_update/spec.worker.replicas' failed with an exception. Will retry.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
result = await invoke_handler(
File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
result = await invocation.invoke(
File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
result = await fn(**kwargs)  # type: ignore
File "/usr/local/lib/python3.10/site-packages/dask_kubernetes/operator/controller/controller.py", line 639, in daskworkergroup_replica_update …
```
> Replace `nil` with `null` in helm chart

- .github/workflows/operator.yaml
- dask_kubernetes/conftest.py
- setup.cfg
We keep seeing hanging CI and it's hard to debug what is going on. Many of these runs have many test failures before locking up. This PR adds the `-x` flag to pytest which will cause it to exit after the first failure. Hopefully this should help get to the bottom of the hangs.
> Tell pytest to fail fast

- dask_kubernetes/aiopykube/tests/test_pykube_objects.py
- dask_kubernetes/aiopykube/tests/test_query.py
- dask_kubernetes/classic/tests/test_async.py
- dask_kubernetes/common/tests/test_kind.py
- dask_kubernetes/conftest.py
- dask_kubernetes/helm/tests/test_helm.py
- dask_kubernetes/operator/controller/tests/test_controller.py
- dask_kubernetes/operator/kubecluster/tests/conftest.py
- dask_kubernetes/operator/kubecluster/tests/test_discovery.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
- requirements-test.txt
- setup.cfg
In https://github.com/dask/distributed/issues/7984 @fjetter and @graingert suggested moving away from `pytest-asyncio`.
This PR updates all tests to use `anyio` but with just the `asyncio` backend.
> Switch pytest-asyncio to use anyio

- dask_kubernetes/operator/controller/controller.py
Just replaces the use of `kubernetes_asyncio` with `kr8s` in `daskworkergroup_replica_update`. 
I also switched the logic that checks how many workers there are currently from listing Pods to Deployments which should fix #773.
> Replace worker replica update code to use kr8s

- dask_kubernetes/operator/deployment/Dockerfile
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
This PR updates the operator container `Dockerfile` and operator deployment manifest (via the values file) to run as non-root, i.e. user 1000 (username `toor`). 
Relevant [issue](https://github.com/dask/dask-kubernetes/issues/776).
I confirmed the image builds, shelled into the running container, and confirmed that I can execute the `kopf` binary as the `dask` user.
> Run operator container as non-root

- dask_kubernetes/operator/controller/controller.py
Just replaces the use of `kubernetes_asyncio` with `kr8s` in `daskcluster_create_components`. Should functionally have no change.
> Replace kubernetes_asyncio with kr8s in daskcluster_create_components

- dask_kubernetes/operator/kubecluster/discovery.py
- setup.cfg
Use kr8s to list Dask Clusters during discovery instead of kubernetes_asyncio. Should functionally have no change.
> Replace kubernetes_asyncio with kr8s in cluster discovery

- dask_kubernetes/common/networking.py
- dask_kubernetes/operator/_objects.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
- requirements-test.txt
- requirements.txt
I'm pulling #785 into a few pieces to try and figure out the failures. This is just everything outside of `kubecluster.py`.
> Small changes form kr8s kubecluster migration

- dask_kubernetes/operator/kubecluster/kubecluster.py
Pulling out another chunk of #785. This one updates `KubeCluster.scale()` and `KubeCluster.adapt()` to use `kr8s`.
> Migrate KubeCluster scale and adapt to kr8s

- dask_kubernetes/operator/kubecluster/kubecluster.py
Pulling out another chunk of #785. This one updates `KubeCluster._close()` to use `kr8s`.
> Migrate KubeCluster close to kr8s

- dask_kubernetes/operator/kubecluster/kubecluster.py
- requirements.txt
Pulling out another chunk of #785. This one updates `KubeCluster._watch_component_status()` to use `kr8s`.
> Migrate KubeCluster component status to kr8s

- dask_kubernetes/common/auth.py
After enabling refresh tokens on our oidc backend (shout out to @harrisonfritz),  dask-kubernetes still failed. I narrowed down the problem to the fact that `parse_rfc3339` is not equipped to handle an `expiration_timestamp` in epoch string format, which is what the OIDC protocol spec specifies (shout out to @DWSR for pointing us to the relevant [docs](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)):
> exp
REQUIRED. Expiration time on or after which the ID Token MUST NOT be accepted for processing. The processing of this parameter requires that the current date/time MUST be before the expiration date/time listed in the value. Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew. **Its value is a JSON number …
> Convert oid expiration timestamp to datetime.datetime

- dask_kubernetes/common/networking.py
Here is an explanation why we have to use `node_port` instead of `port` when service type is `NodePort`: https://stackoverflow.com/a/41510604/983577
> Fix port number when use NodePort (#806)

- dask_kubernetes/common/networking.py
- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/kubecluster/kubecluster.py
- dask_kubernetes/operator/networking.py
- requirements.txt
- Instead of calling `kubectl port-forward` in a subprocess use a `kr8s` port forward in a thread.
- Use kr8s to list nodes when using `NodePort`.
- Use kr8s to get the scheduler Service information.
- Remove unused `kubernetes` authentication from the controller and KubeCluster.
> Use kr8s in common networking

- dask_kubernetes/operator/controller/controller.py
- doc/source/index.rst
- doc/source/operator_troubleshooting.rst
In https://github.com/dask/dask-kubernetes/issues/807 @BitTheByte was experiencing the LIFO scaling mode which can result in unpleasant behaviour where workers get killed when they are not ready. It took some time to figure out what was happening. 
This PR promotes the log message that is triggered when this happens to warning level to help other users who may debug this in the future.
> Promote LIFO scaling log to warning level

- dask_kubernetes/__init__.py
- dask_kubernetes/classic/kubecluster.py
- dask_kubernetes/classic/tests/test_async.py
- dask_kubernetes/helm/helmcluster.py
For some time we've had a deprecation warning when users do `from dask_kubernetes import KubeCluster`. 
Now that the operator is more stable and is fully migrated to kr8s it's time for the classic `KubeCluster` and the `HelmCluster` to go away. This PR adds a more forceful deprecation warning to those classes ahead of full removal.
> Add more deprecation warnings ahead of removing old code

- .pre-commit-config.yaml
- ci/pre-commit-crd.py
- dask_kubernetes/__init__.py
- dask_kubernetes/classic/__init__.py
- dask_kubernetes/classic/kubecluster.py
- dask_kubernetes/classic/tests/test_async.py
- dask_kubernetes/classic/tests/test_sync.py
- dask_kubernetes/cli/cli.py
- dask_kubernetes/common/auth.py
- dask_kubernetes/common/networking.py
- dask_kubernetes/common/objects.py
- dask_kubernetes/common/tests/test_kind.py
- dask_kubernetes/common/tests/test_objects.py
- dask_kubernetes/config.py
- dask_kubernetes/conftest.py
- dask_kubernetes/helm/helmcluster.py
- dask_kubernetes/helm/tests/test_helm.py
- dask_kubernetes/operator/_objects.py
- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/test_controller.py
- dask_kubernetes/operator/kubecluster/discovery.py
- dask_kubernetes/operator/kubecluster/tests/test_discovery.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
- dask_kubernetes/operator/networking.py
- pyproject.toml
- setup.py
This PR adds [ruff](https://github.com/astral-sh/ruff) to the pre-commit hooks and resolves linting violations listed by an execution of `pre-commit run --all-files`. A few errors are ignored, namely:
- [F401](https://www.flake8rules.com/rules/F401.html) since it complains about unused imports in all of the `__init__.py` files.
- [E402](https://www.flake8rules.com/rules/E402.html) since the auto-generated `conf.py` begins with comments rather than imports.
- [E501](https://www.flake8rules.com/rules/E501.html) since there are so many violations (around 70), particularly in `controller.py`. If this is enforced, it might make sense to handle the remediation in a discrete PR. 
Issue: https://github.com/dask/dask-kubernetes/issues/814
> Add ruff to pre-commit and run against all files

- dask_kubernetes/operator/kubecluster/kubecluster.py
This PR fixes a small bug that I ran into trying to run the SDK from my local machine. If resources were not passed and there was no `~/.config/dask/kubernetes.yaml` file, it would try to parse `self.resources` when `self.resources` was set to its default, `None`.
> Avoid parsing resources when None

- dask_kubernetes/operator/kubecluster/kubecluster.py
When `custom_cluster_spec` is passed, `name` is no longer required. This PR updates the docstring to avoid confusion on this point.
> Clarify name parameter docstring

- dask_kubernetes/operator/kubecluster/kubecluster.py
- requirements.txt
In kr8s 0.9.0 (https://github.com/kr8s-org/kr8s/pull/182) the `kr8s.asyncio.objects.Pod.logs()` method changed from returning a string of all the logs to being a generator of each log line. 
This PR tweaks our usage to work with that.
> Fix pod logs

- dask_kubernetes/operator/kubecluster/kubecluster.py
This parameter is available in the parent class but not exposed in `KubeCluster`.
> Add quiet parameter to KubeCluster

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/deployment.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
In https://github.com/dask/dask-kubernetes/issues/684 we were discussing that adding `priorityClassName` might help with configurability of dask kubernetes operator. Especially, settings [priority class](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) to some high priority class might help operator being unable to start after restart because of other resources. Tested manually locally both with `priorityClassName` set and left out.
> Add priorityClassName value to operator deployment

- .github/workflows/helmcluster.yaml
- .github/workflows/kubecluster.yaml
- .github/workflows/operator.yaml
Seeing some CI failures on Kubernetes 1.24 because some charts installed in CI do not support it. Taking the opportunity to upgrade to more recent Kubernetes versions.
> Bump max Kubernetes in CI to 1.29 and minimum to 1.26

- doc/requirements-docs.txt
Docs builds are failing here. Following the workaround from https://github.com/dask/dask-sphinx-theme/issues/68 for now.
> Add sphinx theme workaround

- dask_kubernetes/operator/controller/controller.py
I introduced a bug in https://github.com/dask/dask-kubernetes/pull/871 which will cause decreasing replicas in a worker group to fail on a key error because `format` requires `cluster_name` to be provided with a key.
> Fix: KeyError on Building Scheduler Name in Replica Count Decrease

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/resources/simpleworkergroup.yaml
- dask_kubernetes/operator/controller/tests/test_controller.py
Should solve https://github.com/dask/dask-kubernetes/issues/873
> Enable overwrites of default environment variables

- .github/workflows/helmcluster.yaml
- .github/workflows/kubecluster.yaml
- .github/workflows/operator.yaml
- README.rst
- dask_kubernetes/operator/controller/controller.py
- doc/source/index.rst
Depends on Dask 3.12 Docker images being available https://github.com/dask/dask-docker/pull/309.
> Add Python 3.12 to CI

- dask_kubernetes/operator/_objects.py
- requirements.txt
> Bump kr8s to 0.14.2

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release-publish.yml
Adding Release Drafter to automatically create a GitHub Release with a changelog when a new tag is pushed.
See https://jacobtomlinson.dev/posts/2024/creating-github-releases-automatically-on-tags/ for more info
> Add Release Drafter CI

- requirements.txt
In `kr8s` version `0.14.3` there was a bug fixed that was reported by a `dask-kubernetes` user. It would be nice if we picked that up automatically. I'm still cautious about unpinning `kr8s` completely until we get to `1.0` with more stability guarantees, but relaxing the `mirco` pin seems reasonable.
> Relax kr8s pin to v0.14.*

- .github/workflows/release.yml
Add missing permissions for publishing the helm chart. I manually published `2024.5.0`.
> Fix publish permissions for chart

- dask_kubernetes/conftest.py
- dask_kubernetes/operator/__init__.py
- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/plugins/noop/noop.py
- dask_kubernetes/operator/controller/tests/test_controller.py
- dask_kubernetes/operator/kubecluster/__init__.py
- dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
- pyproject.toml
- requirements-test.txt
General code quality improvements for the controller part of this repository.
- Make sure exported symbols are correctly set in `__init__.py` with `__all__`.
- Renamed pytest fixture for creating a k8s namespace from `ns` to `namespace` since `ns` is a bit overloaded, especially in `test_controller.py`
- Introduce typehints in `controller.py` and `test_controller.py` to massively improve developer experience (previously, one just really had to guess what functions are for and which types are expected)
- Removed unused function parameters
- Made function headers (i.e. parameter [type] defintion) compatible with what `kopf.on.[create/change/...]' expects
- Introduce mypy (and missing stubs of external packages if available)
- Introduce mypy ignores for (still) untyped parts of the codebase …
> Draft: Introduce typehints in controller

- dask_kubernetes/operator/go_client/pkg/apis/kubernetes.dask.org/v1/types.go
This pull request addresses a mismatch identified between the declared Custom Resource Definitions (CRDs) for Kubernetes resources and the `DaskAutoscalerSpec` struct in the Go client.
The issue lies with the `minimum` and `maximum` attributes in the `DaskAutoscalerSpec` struct, which were initially declared as `string` types but should be `int`, as declared in the CRDs. This disparity causes issues between the Go client and the registered Kubernetes scheme.
I have resolved this bug by altering the `DaskAutoscalerSpec` struct to use `int` for the `max` and `min` attributes, ensuring consistency with the CRD. Subsequently, I ran the code autogeneration script to validate that there are no adverse side-effects from these changes.
Thank you for your consideration.
> Fix: Mismatch between declared CRDs and struct for DaskAutoscalers

- .github/workflows/operator.yaml
- README.rst
- dask_kubernetes/operator/_objects.py
- docs/source/index.rst
- pyproject.toml
In `kr8s==0.17` you can now use `new_class` as part of a class constructor. This avoids the need to manually subclass `APIObject` and should lead to more error free code.
With `kr8s==0.17` only Kubernetes `>=1.28` is supported and I'm noticing some CI failures with Kubernetes `1.26` so taking this opportunity to bump the Kubernetes CI versions.
I've also replaced the use of `api.get(Type.endpoint, ...)` with `Type.list(...)` which is a little more readable.
> Bump kr8s to 0.17 and Kubernetes supported versions

- .github/workflows/operator.yaml
- README.rst
- docs/source/index.rst
- pyproject.toml
Dask has ended Python 3.9 support https://github.com/dask/community/issues/373. Removing it from CI and bumping minimum version.
> Drop Python 3.9

- docs/source/index.rst
> Fix Autoscaler example code snippet on the docs index page

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/networking.py
> Fix loadBalancer attribute name

- dask_kubernetes/operator/controller/controller.py
Fallback to finding deployments rather than worker for deletion, as otherwise the pod can have the incorrect name, leading to workers not scaling down in adaptive mode.
Believe this was part of the issue on https://github.com/dask/dask-kubernetes/issues/910
> Improve retire_worker fallback by finding deployments name instead of pod name

- docs/source/index.rst
I hope you don't mind such a small PR—I noticed a minor typo in a section header in the docs, and thought I'd submit a correction.
Thanks for all you do,
Jacob
> Fix section header typo in documentation

- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/README.md
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/deployment.yaml
- dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml
Fixes #917
Plain helm install:
```
Liveness:      http-get http://:8080/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
```
With `--set livenessProbe.timeoutSeconds=5`:
```
Liveness:      http-get http://:8080/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
```
> feat: Add configurable liveness probe timeout

- dask_kubernetes/operator/controller/controller.py
- dask_kubernetes/operator/controller/tests/test_controller.py
The `retire_workers` method will call the scheduler api `/api/v1/retire_workers` first, if it fails it will try the rpc counterpart, if it fails it will finally simply retire the most recent worker deployments, last in first out.
When the autoscaler changes the number of worker replicas based on the scheduler need, it will automatically trigger this method:
```
@kopf.on.field("daskworkergroup.kubernetes.dask.org", field="spec.worker.replicas")
async def daskworkergroup_replica_update
```
The workers needed are then computed through:
```
workers_needed = desired_workers - current_workers
```
where `desired_workers` is the number of replicas required and `current_workers` is the number of deployed pods.
Let's say that for instance the desired number of replicas is 18 and the current number …
> 🐛 Fix retire_workers LIFO fallback issue.

- dask_kubernetes/operator/kubecluster/kubecluster.py
Minor docs change to reflect that the `env` parameter of `KubeCluster` will set the environment variables on the scheduler (in addition to workers).
See that this is the case [here](https://github.com/dask/dask-kubernetes/blob/30cc719850afb6a5d4482e0df867d2368db000e0/dask_kubernetes/operator/kubecluster/kubecluster.py#L877) in `make_cluster_spec(...)`, that function's doc string is correct. But if you are like me you may only look at the doc string on `KubeCluster` in an LSP annotation / [on the docs](https://kubernetes.dask.org/en/latest/operator_kubecluster.html#api)
> Reflect that `env` will set on scheduler too

- dask_kubernetes/conftest.py
CI is failing because the latest `2025.4.0` release of the [dask-gateway helm chart](https://artifacthub.io/packages/helm/dask/dask-gateway/2024.1.0) doesn't support Kubernetes <1.30.
This PR updates the conftest to pin the version of dask-gateway to `2024.1.0` if the Kubernetes version is <1.30.
> Pin dask-gateway version for tests on older Kubernetes versions

- .github/workflows/lint.yaml
- dask_kubernetes/operator/controller/controller.py
All controller event handlers should be idempotent, however as seen in #940 if the controller is restarted while the job creation handler is being run it will get stuck in a failure loop.
This PR adds some quick checks to skip over resources that already exist.
Closes #940
> Skip Job cluster creation if already exists

- dask_kubernetes/kubernetes.yaml
- dask_kubernetes/operator/controller/controller.py
Closes #945 
Allows users to set which log messages get emitted as Kubernetes events. Configurable via the Dask config system which allows setting via a `ConfigMap` or environment variables.
```
DASK_KUBERNETES__CONTROLLER__EVENTS__ENABLED=true
DASK_KUBERNETES__CONTROLLER__EVENTS__LEVEL="INFO"
```
> Allow configuring the event emit level

- pyproject.toml
There was a bug tracked in #913 that was fixed upstream in `kopf` version `1.38.0`. This PR bumps the minimum version to that to ensure everyone gets the fix.
> Bump the minimum kopf version to 1.38.0
